export const trendingData = {
    "lastUpdatedTime": "ty9SJ_wrReI",
    "trendingVideos": [
        {
            "id": "f5099e39-f0d2-4b2d-b40f-e54b0e8fad2f",
            "videoId": "ty9SJ_wrReI",
            "title": "#Video | #Khesari Lal Yadav New Song | तबला | #Shilpi Raj | #Namrita Malla | Tabla",
            "thumbnail": "https://i.ytimg.com/vi/ty9SJ_wrReI/maxresdefault.jpg",
            "duration": "PT3M48S",
            "description": "इंतजार हुआ खत्म मचाओ सब धमाल आ गया खेसारी भईया का \"तबला\" तो झूमो, नाचो, गाओ और मिलाओ ताल से ताल...\n\nख़रीदिए कारवाँ मोबाइल- 1500 प्रीलोडिड गानों वाला कीपैड फ़ोन धमाकेदार साउंड के साथ\nhttp://sarega.ma/ycmbuy\n\nCredits:\n🎤Singer - Khesari Lal Yadav & Shilpi Raj\n💃Feat - Namrita Malla\n✍️Writer - DK Deewana\n🎵Music - Shubham Raj (SBR)\n🎥Video By - Team Sanju\n🎥Video Director - Sooraj Katoch\n✂️Editor - P.Shubham Babu & Shrikant (ZAV Studio)\n🎥EP - Sitosh Yadav\n📸DOP - Yogesh Singh\n🎥Art Director - Puneet Kapoor\n👗Costumes - ZAI Fashion (Reema)\n💃Dancers - Zenith Dance Troupe\n💃Choreographer - Geeta Tamta\n💄Makeup - Govind (Double G)\n🎥 Production- Nitesh singh \n🎥 DI - Rohit Singh\n\n#Khesari Lal Yadav के बवाल गाने सुनने के लिए आज ही Subscribe करे \nhttps://bit.ly/Saregamahumbhojpuri \n\n#khesari \n#Tabla  \n#khesarilalyadav \n#khesarilal  \n#namritamalla \n#shilpiraj \n#bhojpuri \n#bhojpurisong \n#bhojpurigana \n\nFollow us on:\nFacebook: https://bit.ly/3FxwPgo \nInstagram: https://bit.ly/32rkJqM\nTwitter: @saregamaglobal \n\nContact for Movie and Album \nBadrinath.jha@rpsg.in\n\nLabel:: Saregama India Limited, A RPSG Group Company",
            "tags": [
                "tabla",
                "Khesari Lal Yadav",
                "Khesari Lal",
                "khesari lal new song",
                "khesari lal song",
                "khesari lal ke gana",
                "khesari lal new song 2022",
                "तबला",
                "Bhojpuri Song",
                "namrita malla",
                "namrita malla bhojpuri songs",
                "namrita malla khesari lal yadav",
                "shilpi raj new songs",
                "nathuniya",
                "apni toh jaise taise",
                "nariyal",
                "mahima mahan",
                "le le aayi coca cola",
                "Bondhu Teen Din",
                "do ghoont bhojpuri",
                "pani pani bhojpuri",
                "Chhath Ghate Chali",
                "Lal Ghaghra",
                "paro",
                "khesari lal yadav new song 2022",
                "tuition wali",
                "baarish",
                "baraf"
            ],
            "channelTitle": "Saregama Hum Bhojpuri",
            "publishedAt": "2022-11-01T05:30:11Z"
        },
        {
            "id": "60a92405-a59e-481b-b0de-b5a3b321f4ab",
            "videoId": "t0hPzfc1pLU",
            "title": "Ranjithame - Varisu Song Promo (Tamil) | Thalapathy Vijay | Rashmika | Vamshi Paidipally | Thaman S",
            "thumbnail": "https://i.ytimg.com/vi/t0hPzfc1pLU/maxresdefault.jpg",
            "duration": "PT31S",
            "description": "Here is the most awaited #VarisuFirstSingle  \" #RanjithamePromoVideo \" of Thalapathy Vijay's #Varisu\n\nFilm Credits:\nDirector: Vamshi Paidipally\nProducer: Raju, Shirish\nBanner: Sri Venkateswara Creations\nCo-Producers: Sri Harshith Reddy, Sri Harshitha\nComposed by Thaman S\nStar Cast: Vijay, Rashmika Mandanna, R Sarathkumar, Prabhu, Prakash Raj, Shaam, Srikanth, Khushbu,\nYogi Babu, Jayasudha, Sangeetha Krish, Samyuktha Shanmughanathan and others.\nStory, Screenplay: Vamshi Paidipally, Hari & Ahishor Solomon\nDialogues, Additional Screenplay, Lyrics: Vivek\nDop: Karthik Palani\nEditor: Praveen KL\nProduction Design: Sunil Babu & Vaishnavi Reddy\nAction: Ram Laxman, Peter Hein & Dhilip Subbarayan\nChoreographer: Jani Master\nCostume Designers: Deepali Noor, Akangshee Chopra (Rashmika Mandanna)\nCo-Director: Rambabu Kongarapi\nMakeup: P Nagarajan\nVFX: Yugandhar\nPro: Riaz K Ahmed\nPublicity Design: Gopi Prasannaa\nStills: D Maneksha\nProduction Controller: Kishore Surapaneni & KTS Swaminathan\nExecutive Producer: B Sreedhar Rao & R Udhayakumar\n\nSong Credits:\nSong Title: #Ranjithame\nAlbum/Movie: Varisu\nSinger: Thalapathy Vijay, M M Manasi\nProgrammed & Arranged By Thaman S\nLyrics: Vivek\nMusic Label: T-Series\n\nMusician Credits:\nAcoustic Drums & Electric Rhythm: Thaman S\nDrums & Band: The Gongura Band & Thamania\nLive Percussions: Anandan Sivamani\nAdditional Live Percussions: Krishna Kishore\nRural & Ethnic Percussions: Karthik Vamsi & Guberan\nTavil:Madhu, Kaviraj, Sundhar, Shruthi Raj\nTape: Lakshmi Narayana, Raju,Jagan Mohan, Jaya Prakash, Lakshmi Kanth & Pyare Lal\nThalam: Veda\nNadaswaram: Sivakumar\nGuitar: Godfrey (CHN)\nMandolin: Subhani (HYD)\nVocal Supervision: Sri Krishna\nFemale Chours: Sahiti Chagati, Ramya behara & Sruthi Ranjani\nSong Recorded @Prasad Studio (Hyd), V Studio (Chennai), Uno Records Studios by Osho V & Biju\nJames\nMixed & Mastered By Shadab Rayeen At\nNew Edge Mumbai & New Edge (Ny)\nAssisted By: Pukhraj & Anup\nMusicians Co Ordinator: Manikandan\nStudio Manager: Seenu\nStudio Assistance: Kannan, Lingam, Raju & Ranjith & Sridhar\n\n___________________________________\nEnjoy & stay connected with us!\n👉 Subscribe to T-Series: http://bit.ly/TSeriesYouTube\n👉 Like us on Facebook: https://www.facebook.com/tseriesmusic\n👉 Follow us on Twitter: https://twitter.com/tseries\n👉 Follow us on Instagram: http://bit.ly/InstagramTseries",
            "tags": [
                "hindi songs 2022",
                "hindi songs new",
                "bollywood songs 2022",
                "bollywood movies 2022",
                "tseries",
                "tseries songs",
                "hindi songs",
                "bollywood romantic songs",
                "romantic hindi songs",
                "hindi songs bollywood",
                "remix hindi songs",
                "hindi song status",
                "bollywood dance songs",
                "Ranjithame (Teaser)",
                "Varisu",
                "Thalapathy Vijay Singing",
                "Thalapathy Vijay Song",
                "Thalapathy Vijay Dance Number",
                "Thalapathy Vijay Ranjithame",
                "Thalapathy Vijay Varisu",
                "Thalapathy Vijay",
                "Vivek",
                "Thaman S"
            ],
            "channelTitle": "T-Series",
            "publishedAt": "2022-11-03T13:00:38Z"
        },
        {
            "id": "e6a41691-5462-4990-9d6c-31d54c398b3f",
            "videoId": "QSYm390lXPs",
            "title": "MA GALLILO OKKADU PORADU FULL SONG TELUGU FOLK SONG 2022 #JOGULAVENKATES #MOUNIKAYADAV #DHARANINAIDU",
            "thumbnail": "https://i.ytimg.com/vi/QSYm390lXPs/maxresdefault.jpg",
            "duration": "PT4M10S",
            "description": "Lyrics : Jogula Venkatesh\nhttps://www.instagram.com/jogula_venkatesh_official\nSinger : Mounika Yadav Mamindla\nhttps://www.instagram.com/mounika_yadav.9\nMusic  : Kalyan Keys\nhttps://www.instagram.com/kalyan_keys\nFlute : Ragava Sai\nD.o.p : Shiva Velpula\nhttps://www.instagram.com/shiva_velupula\nDirection & Editing : Harish Velpula\nhttps://www.instagram.com/harish_velpula\nD.I & Titles : Anneboina Srinivas\nPoster Designer : Sagar Mudiraaz\nDrone :  Suresh Degavath , Harish Kanna\nCast : Dharani Naidu , Jogula Venkatesh\nMaking Video : Anil Radha\nMakeup : Rajesh\nPublicity : Nenu Mee Barath \nAssst Camera : Babu\nSpecial Thanks : Ragavendhar Reddy ( R Square Media )\nActors : \nRaja Goud\nAnnapurna\nMallesham\nHimakar Bhatt\nBhuvaneshwari\nGayatri\nSameera\nShankar\nKistanna\nKomuraiah\nSrinivas\n\n\nSpecial Thanks :\nJalendhar MJ \nSathish B \nRAJU COOL MUSIC\nMittapalli Surendhar\nShailendhar Reddy\nNarendhar Reddy \nSrikanth Peddapelli\nRowdy Harish\nRajesh Malyala   \nDurgam Mahesh\nAravind Goud\nSanthosh EGP\nPrasad\nRacha Shekar\nPraveen\nAbhi\nKalyan khamma kurrodu",
            "tags": [
                "latest folk songs",
                "jogula venkatesh folk songs",
                "jogula venkatesh songs",
                "Kalyan key's folk songs",
                "Telugu folk songs",
                "new folk songs",
                "MA GALLILO OKKADU PORADU",
                "Telangana Folk songs",
                "latest folk songs jogula venkatesh",
                "MOUNIKAYADAV",
                "Telugu folk songs 2022",
                "mounika Yadav folk songs",
                "mounika Yadav latest folk songs",
                "dj Folk song",
                "DHARANINAIDU"
            ],
            "channelTitle": "Jogula Venkatesh Official",
            "publishedAt": "2022-11-03T11:00:11Z"
        },
        {
            "id": "a70d7270-25a0-4cea-b7cd-12a5754c39d9",
            "videoId": "zuVV9Y55gvc",
            "title": "Ranjithame - Varisu Lyric Song (Tamil) | Thalapathy Vijay | Rashmika | Vamshi Paidipally | Thaman S",
            "thumbnail": "https://i.ytimg.com/vi/zuVV9Y55gvc/maxresdefault.jpg",
            "duration": "PT4M50S",
            "description": "Here is the most awaited first single \"Ranjithame\" lyric video of Thalapathy Vijay’s #Varisu. \n\nFilm Credits:\n\nDirector: Vamshi Paidipally \nProducer: Raju, Shirish\nBanner: Sri Venkateswara Creations\n\nCo-Producers: Sri Harshith Reddy, Sri Harshitha \nComposed by Thaman S\n\nStar Cast: Thalapathy Vijay, Rashmika Mandanna, R Sarathkumar, Prabhu, Prakash Raj, Shaam, Srikanth, Khushbu, Yogi Babu, Jayasudha, Sangeetha Krish, Samyuktha Shanmughanathan, Nandini Rai, Ganesh Venkatraman, Sriman, VT Ganesan, John Vijay, Bharath Reddy, Sanjana and others.\n\nStory, Screenplay: Vamshi Paidipally, Hari & Ahishor Solomon Dialogues, Additional Screenplay, Lyrics: Vivek\nDop: Karthik Palani Editor: Praveen KL\nProduction Design: Sunil Babu & Vaishnavi Reddy \nAction: Ram Laxman, Peter Hein & Dhilip Subbarayan \nChoreographer: Raja Sundaram, Shobi & Jani\nCostume Designers: Deepali Noor, Akangshee Chopra (Rashmika Mandanna) \nCo-Director: Rambabu Kongarapi\nMakeup: P Nagarajan \nVFX: Yugandhar\nPro: Riaz K Ahmed\n\nPublicity Design: Gopi Prasannaa \nStills: D Maneksha\nProduction Controller: Kishore Surapaneni & KTS Swaminathan\n \nExecutive Producer: B Sreedhar Rao & R Udhayakumar \nAssociate Editor: M Sandeep\nAssociate Cinematographer: Lokesh Ilayaa \nSecond Camera operator: N V Reddy\nAssistant Cinematographers: Sarath Krishna. R, Yadhavan Subramaniam, Thiyagu G, Sandeep Bapatla & Vivian Pullan\n\nVirtual Production (ICVFX): Stage Unreal Pvt Ltd. \nVirtual production VFX supervisor: Srinivas Mohan \nVirtual Production Producer: Manoj Paramahamsa \nDigital Cinema Designer: G Balaji\nVirtual Cinematographer: Raam\n\nUnreal Engine Artist & n Display Technician: Nesikaa Rajakumaran Technical Artist: Salahudeen M\nAdditional Unreal Engine Artists: Manigandan G | P vignesh waran | P Gokula Krishna\nModeling Artist Amaljith.KT\n\nSong Credits:\n\nSong Title: Ranjithame \nAlbum/Movie: Varisu\nSinger: Thalapathy Vijay, M M Manasi \nProgrammed & Arranged By Thaman S \nLyrics: Vivek\n\n\nMusician Credits:\n\nAcoustic Drums & Electric Rhythm: Thaman S\n \nDrums & Band: The Gongura Band & Thamania \nLive Percussions: Anandan Sivamani\nAdditional Live Percussions: Krishna Kishore\n\nRural & Ethnic Percussions: Karthik Vamsi & Guberan \nTavil: Madhu, Kaviraj, Sundhar, Shruthi Raj\nTape: Lakshmi Narayana, Raju,Jagan Mohan, Jaya Prakash, Lakshmi Kanth & Pyare Lal \nThalam: Veda\nNadaswaram: Sivakumar \nGuitar: Godfrey (CHN) \nMandolin: Subhani (HYD) \nVocal Supervision: Sri Krishna\nFemale Chours: Sahiti Chagati, Ramya behara & Sruthi Ranjani\n\nSong Recorded @Prasad Studio (Hyd) ,V Studio ( Chennai ) , Uno Records Studios by Osho V & Biju James\n\nMixed & Mastered By Shadab Rayeen At \nNew Edge Mumbai & New Edge (Ny) \n\nAssisted By: Pukhraj & Anup\nMusicians Co Ordinator: Manikandan Studio \nManager: Seenu\nStudio Assistance: Kannan, Lingam, Raju & Ranjith & Sridhar\n\n___________________________________\nEnjoy & stay connected with us!\n👉 Subscribe to T-Series: http://bit.ly/TSeriesYouTube\n👉 Like us on Facebook: https://www.facebook.com/tseriesmusic\n👉 Follow us on Twitter: https://twitter.com/tseries\n👉 Follow us on Instagram: http://bit.ly/InstagramTseries",
            "tags": [
                "hindi songs 2022",
                "hindi songs new",
                "bollywood songs 2022",
                "bollywood movies 2022",
                "tseries",
                "tseries songs",
                "hindi songs",
                "bollywood romantic songs",
                "romantic hindi songs",
                "bollywood dance songs",
                "Ranjithame (Lyrical)",
                "Varisu",
                "Thalapathy Vijay Singing",
                "Thalapathy Vijay Song",
                "Thalapathy Vijay Dance Number",
                "Thalapathy Vijay Ranjithame",
                "Thalapathy Vijay Varisu",
                "Thalapathy Vijay",
                "Vivek",
                "Thaman S",
                "Varisu Lyric Song (Tamil)",
                "Ranjithame Lyric Song",
                "Ranjithame Video Song",
                "Ranjithame",
                "Tamil Song"
            ],
            "channelTitle": "T-Series",
            "publishedAt": "2022-11-05T12:00:42Z"
        },
        {
            "id": "ea1a1892-ddf4-4856-b27f-ab5c4be79950",
            "videoId": "um3h13KJRxg",
            "title": "Sidhu Moose Wala - Vaar",
            "thumbnail": "https://i.ytimg.com/vi/um3h13KJRxg/maxresdefault.jpg",
            "duration": "PT2M18S",
            "description": "Song : Vaar\nSinger, Composer : Sidhu Moose Wala\nMusic Producer : Snappy\n Mix & Master - Rass\nVisuals : Navkaran Brar\nPromotions : Gold Media Entertainment\nDigital Powered by: One Digital Entertainment \nLabel : Sidhu Moose Wala\n\nStay Tuned On - \nSpotify - https://spoti.fi/3FTygsw\niTunes - https://apple.co/3UiPbZX\nJioSaavn - https://bit.ly/3fN9q2Q\nResso - https://bit.ly/3zYhrsB\nYouTube Music - https://bit.ly/3DOXl5b\n\nClick to Subscribe - https://bit.ly/SidhuMooseWalaSubscribe\nTwitter - https://www.twitter.com/iSidhuMooseWala\nFacebook - https://www.facebook.com/SidhuMooseWala\nInstagram - https://instagram.com/Sidhu_MooseWala\nSnapChat - https://www.snapchat.com/add/SidhuShubh",
            "tags": [
                "sidhu moose wala vaar",
                "sidhu moose wala gana",
                "sidhu moose wala vaar song",
                "sidhu moose wala ke gane",
                "sidhu moose wala news",
                "sidhu moose wala live",
                "sidhu moose wala ringtone",
                "sidhu moose wala reaction",
                "sidhu moose wala all song",
                "sidhu moose wala new song",
                "sidhu moose wala live concert",
                "sidhu moose wala new leak song",
                "sidhu moose wala new song today",
                "vaar sidhu moose wala",
                "vaar song sidhu moosewala",
                "moosewala leaked song",
                "hari singh nalwa"
            ],
            "channelTitle": "Sidhu Moose Wala",
            "publishedAt": "2022-11-08T04:30:08Z"
        },
        {
            "id": "cce8f817-b1c9-4a97-affa-310d6def3b35",
            "videoId": "sek3FhByr6w",
            "title": "DIVINE - Baazigar feat. Armani White | Prod. by Karan Kanchan | Official Audio",
            "thumbnail": "https://i.ytimg.com/vi/sek3FhByr6w/maxresdefault.jpg",
            "duration": "PT2M48S",
            "description": "Download & Stream: https://gg.lnk.to/gunehgar-album\n\nAlka Yagnik’s impeccable vocals make an unforeseen appearance on the second track from ‘Gunehgar’, as producer Karan Kanchan samples ‘Bazigar o bazigar’. And as the duo did on Satya, they make yet another rap banger out of a classic bollywood tune. Armani White, the ‘Billie Eilish’ hitmaker hops on the track and to no surprise drops a stylish verse as his smooth vocal delivery serves as a delightful contrast to DIVINE aggressive and rugged vocals.\n\nAudio Credits:\n\nTrack: Baazigar \nArtist: DIVINE\nFeaturing Artist: Armani White \nLyrics: DIVINE, Armani White\nCo-Composers: DIVINE,  Armani White, Karan Kanchan, Anu Malik,  Nawab Arzoo\nProduced by: Karan Kanchan\nMixed by: Hanish Taneja\nMastered by: Hanish Taneja\nLabel: Gully Gang / Mass Appeal\n\nVideo Credits:\n\nEdited by: Sasta Acid \n\nFollow DIVINE: \nhttps://www.instagram.com/vivianakadivine/\nhttps://twitter.com/viviandivine\nhttps://www.facebook.com/viviandivineindia\n\nFollow Gully Gang:\nhttps://www.instagram.com/gullygangindia/\nhttps://twitter.com/gullygangindia\nhttps://www.facebook.com/GullyGangOfficial/\n\nFollow Mass Appeal India: \nhttps://www.instagram.com/massappealindia/\nhttps://www.facebook.com/massappealindia\nhttps://twitter.com/massappealindia",
            "tags": [],
            "channelTitle": "DIVINE",
            "publishedAt": "2022-11-09T18:30:50Z"
        },
        {
            "id": "f734ade0-32c5-4cb1-b832-58183e48ff9b",
            "videoId": "mNuhKUOD_A0",
            "title": "Deva Deva - Extended Film Version|Brahmāstra|Amitabh B | Ranbir |@Alia Bhatt|@Pritam |Arijit|Jonita",
            "thumbnail": "https://i.ytimg.com/vi/mNuhKUOD_A0/maxresdefault.jpg",
            "duration": "PT5M52S",
            "description": "With never-before-seen footage, watch Shiva unlock his power in “Deva Deva – Extended Film Version”, also starring Amitabh Bachchan. Composed by Pritam, written by Amitabh Bachchan and sung by Arijit Singh and Jonita Gandhi, add this to your motivation playlist for an added boost!\n\n#DevaDevaExtendedFilmVersion #Brahmastra \n\n#DevaDeva #Brahmastra #RanbirKapoor #AliaBhatt #AmitabhBachchan #ArijitSingh #Pritam  #AyanMukerji #AmitabhBhattacharya  \n\nListen to the album here: SMI.lnk.to/Brahmastra\n\nMusic – Pritam\nLyrics - Amitabh Bhattacharya\nSingers - Arijit Singh & Jonita Gandhi\nMusic Arrangement and Production - Johan Folke, Chris Wetterström, Arijit Singh, Sunny M.R., Aditya N. & Somanshu Agarwal\nSound Design - Sunny M.R., DJ Phukan and Ashwin Kulkarni\nMix & Master – Shadab Rayeen at New Edge\nChief Engineer & Shootmix - Ashwin Kulkarni\nMusic Production Manager - Anurag Sharma\nSound Engineers - Ashwin Kulkarni, Aniruddh Anantha, Pranav Gupta, Harjot Kaur, Aaroh Velankar & Himanshu Shirlekar\nMusic Team - Aniruddh Anantha , Dev Arijit, Antara Mitra, Tushar Joshi & Akashdeep Sengupta\nBacking vocals designed - Aditya N., Tushar Joshi, Arjun Chandy and Aniruddh Anantha\nMixing Assistant to Shadab – Pukhraj Sonkar and Anup Gandharla\nEngineers at JAM8 - Subhashree Das & Akash Mukherjee\nRecording Engineer to Arijit Singh - Sukanto Singha\nMusicians: -\nGuitars - Chris Wetterström, Aditya Shankar Benia & Roland Fernandes\nModular Synths - Sunny M.R. & ZIA (Chordfather Productions)\n\nBacking Vocals - Aditya N., Ashwin Kulkarni, Aniruddh Anantha, Anurag Sharma, Dev Arijit, Tushar Joshi, Aaroh Velankar, Himanshu Shirlekar, Shloke Lal, Thomson Andrews, Suhas Sawant, Rajiv Sundaresan, Rahul Pandey, Arun Haridas Kamath, Umesh Joshi, Gwen Dias, Crystal Sequeira Karnad, Marianne D'Cruz Aiman, Enid Mendonca, Samantha Noella and Keshia Braganza\n\nChoreography - Brinda Gopal, Adil Shaikh\nProduced by Fox Star Studios, Dharma Productions, Prime Focus and Starlight Pictures\nMusic by Pritam\nMusic on Sony Music India\nDirected by Ayan Mukerji\nStarring Amitabh Bachchan, Ranbir Kapoor, Alia Bhatt, Mouni Roy and Nagarjuna Akkineni\n\nLyrics:\nMALE-\nChingariyan ye jo mere seene mein hain dafan\nInko zara deke hava ban jaaun main agan\n\nDahek raha hai banke sharara dekh mera badan\nSab kuchh mera karke fanaa karta hoon main havan\n\nOm Deva Deva\nOm Deva Deva namah\nNamaho Namah Om\n\nOm Deva Deva\nOm Deva Deva namaha…\nNamaho Namah Om\n\nMehsoos ख़ुद ko maine kiya jab tu ne chhua\n\nOm Deva Deva\nOm Deva Deva namah\n\nNamaho Namah Om\n\nANTARA- 1\nMALE-\n\nKitni hi dafa maine dekh ke \nAdekhe kiye angaaron ke ख़ुद mein निशाँ\n\nNa inko mili kabhi disha\n\nMain toota hua vo sitaara nahin\nबेदख़ल jise kar chuka ho yeh aasmaan\n\nMain ख़ुद mein hoon ek kahkashaan\n\nShikve puraane saare peechhe main chhodta hoon\nUgte sooraj se apni\nUmmeedein jodta hun\n\nDuniyaan badalne meri aaya hai yeh lamha\nLamha...\n\nOm Deva Deva\nOm Deva Deva namah\nNamaho Namah Om\n\nOm Deva Deva\nOm Deva Deva namah\n\nNamaho Namah Om\n\nMehsoos ख्रुद ko maine kiya...\nJab tune chhua\n\nOm Deva Deva\nOm Deva Deva namah\nNamaho namah om\n\nANTARA – 2\nFEMALE-\n\nIshq humara nahin ye fitoor hai \nRishta purana koi toh zaroor hai\n\nAake mile hain usi ke toh vaaste \nYe raaste .. ye raaste\n\nMALE-\nTu hai havaon ka jhonka main aag hoon\nTu raagdaari hai meri main raag hoon\n\nMain jee raha hoon tere intezar mein\nAavaaz de .. aavaaz de\n\nTERI SARAAYE dhoondh raha tha mera banjaara man\n\nSab such mere karke fanaa\nKarta hoon main havan\n\nOm Deva Deva\nOm Deva Deva namah\nNamaho Namah Om\n\nOm Deva Deva\nOm Deva Deva namah\nNamaho Namah Om\n\nMehsoos ख़ुद ko maine kiya...\nJab tune chhua\n\nOm Deva Deva\nOm Deva Deva namah\nNamaho Namah Om\n\nAudio on Sony Music Entertainment India Pvt. Ltd (C) 2022\n👉 Subscribe To Sony Music India YouTube - http://bit.ly/SonyMusic_YouTube\n👉 Like us : Facebook - https://www.facebook.com/SonyMusicIndia \n👉 Follow us : Instagram - https://www.instagram.com/sonymusicindia\n👉 Follow us : Twitter - https://twitter.com/sonymusicindia",
            "tags": [
                "Sony Music India",
                "Sony Music",
                "Latest Hits",
                "trending song 2022",
                "Kesariya",
                "Kesariya full song",
                "kesariya song",
                "kesariya tera song",
                "Brahmastra",
                "Ranbir Kapoor",
                "Alia Bhatt",
                "New movie 2022",
                "New song 2022",
                "brahmastra",
                "ranbir kapoor and alia bhatt",
                "Arijit singh",
                "Arijit Singh New Song",
                "Trending songs",
                "Amitabh Bachchan",
                "Mouni Roy",
                "Nagarjuna Akkineni",
                "Kesariya Status",
                "Kesariya Reels",
                "Pritam",
                "love storiyan",
                "love storiyaan",
                "Deva Deva",
                "Ayaan Mukherjee",
                "Deva",
                "Shiva",
                "Shiv Parvati"
            ],
            "channelTitle": "Sony Music India",
            "publishedAt": "2022-11-11T05:31:05Z"
        },
        {
            "id": "454929eb-983f-44b2-b256-a0828868de6c",
            "videoId": "14nAMb8bYSk",
            "title": "Ponni Nadhi - Full Video | Ponniyin Selvan 1 | Tamil | AR Rahman | Mani Ratnam | Karthi",
            "thumbnail": "https://i.ytimg.com/vi/14nAMb8bYSk/maxresdefault.jpg",
            "duration": "PT4M59S",
            "description": "Subaskaran Presents\nA Mani Ratnam Film\nPonniyin Selvan Part-1\nAn AR Rahman Musical\nBased on Kalki’s \"Ponniyin Selvan\"\n\nStay updated with the latest videos from Tips Tamil, Subscribe on the below link\nLink: https://www.youtube.com/c/TipsTamil\n\nSong Title: Ponni Nadhi - Tamil\nAlbum: Ponniyin Selvan Part - 1\nSong Composed and Arranged by A.R.Rahman\nSingers: A.R.Rahman, AR Raihanah, Bamba Bakya\nLyrics: Ilango Krishnan\nMusic Supervisor: Nakul Abhyankar \nLyrical Supervision: Sreekanth Hariharan\nMusicians: \nShehnai - Balesh\nFlute - Kamalakar\nViolin - Vignesh\nString Instruments - SM Subhani\nPercussion - Guberan, Ranjith, Hariprasad, Kishore\nLead Drummer - SIVAMANI\nBacking Vocals:  Sarthak Kalyani, Swagat Rathod, Rakshita Suresh, Pooja Tiwari, Aparna Narayanan, Aparna Harikumar, Vrusha Balu, Pooja Venkat, Anu Anand\nAdditional Programming: Nakul Abhyankar, Shubham Bhat\nRhythm Programming: Kumaran Sivamani\nSound Engineers: Panchathan Record inn\nSuresh Permal, Karthik Sekaran, Aravind Cresendo, Suryansh, Sarthak Kalyani, Nitish R Kumar\nAM Studios\nSivakumar, Pradeep Menon, Manoj Raman, Sathya, Ainul\nMixed by Suresh Permal\nMastered by Suresh Permal\nApple Digital Master by Riyasdeen Riyan\nMusician Coordinator: Samidurai R, Velavan B, Abdul Haiyum, Siddique, T M Faizudeen\n\nMovie Details : \nBanner: Lyca Productions & Madras Talkies\nMovie Name: Ponniyin Selvan Part - 1\nCast: Vikram, Aishwarya Rai Bachchan, Jayam Ravi, Karthi, Trisha, Prabhu, R Sarath Kumar, Aishwarya Lekshmi, Sobhita Dhulipala, Vikram Prabhu, Jayaram, Prakash Raj, Rahman and Radhakrishnan Parthiban. \nDoP: Ravi Varman\nEditor: Sreekar Prasad\nProduction Designer: Thota Tharrani\nChoreography: Brinda\nCostume Designer: Eka Lakhani\nAdditional Costume Designer: Chandrakant Sonawane\nJewellery: Kishandas & Co\nHair & Make Up: Vikram Gaikwad\nAction: Kecha Khamphakdee & Sham Kaushal\nVFX: NYVFXWaala\nVFX Supervisor: Sanjiv Anand Naik\nDI: Red Chillies Color\nColorist: Ken Metzker\nRe-Recording Mixer: Craig Mann\nAdditional Re-Recording Mixer: S Sivakumar\nSound Designer: Anand Krishnamoorthi\nBackground Score Supervisor: Tuomas Kantelinen        \nMusic Supervisor: Nakul Abhyankar             \nPanchatan Sound Engineers: Suresh Permal, Karthik Sekaran & Aravind Cresendo\nStills: CH Balu\nPublicity Designs: Gopi Prasannaa\nPromo Editor: E.Sangathamizhan\nDigital Streaming Partner: Amazon Prime Video\nMusic Lable: TIPS\nLyca Productions:\nHead- G.K.M. Tamil Kumaran\nCEO- Aashish Singh\nLyrics: Ilango Krishnan, Kabilan, Siva Ananth & Krithika Nelson\nDialogues: Jeyamohan\nScreenplay: Mani Ratnam, Jeyamohan & Kumaravel\nExecutive Producer: Siva Ananth\nProduced By: Mani Ratnam & Subaskaran\nDirected By: Mani Ratnam\n\n#ponninadhi  #ps1 #ponniyinselvan #arrahman #maniratnam #karthi #trishakrishnan #tamilsongs #tamilmovies2022 #tamilmovie2022 \n\nJoin Us On:\nhttps://www.youtube.com/c/TipsTamil\nhttps://www.youtube.com/c/tipsofficial\nhttps://www.youtube.com/c/jhankargaane\nhttps://www.youtube.com/c/90sGaane\nhttps://www.youtube.com/c/TipsFilms\nhttps://www.youtube.com/c/TipsPunjabi\nhttps://www.youtube.com/c/TipsBhojpuri\nhttps://www.youtube.com/c/TipsMarathi\nhttps://www.youtube.com/c/bhaktiprem\nhttps://www.youtube.com/c/volume\nhttps://www.youtube.com/c/TipsRajasthani\nhttps://www.youtube.com/c/TipsHaryanvi\nhttps://www.youtube.com/c/TipsIbadat\nhttps://www.youtube.com/c/TipsGujarati\nhttps://www.youtube.com/c/TipsTelugu\nhttps://www.youtube.com/c/TipsMalayal...\nhttps://www.youtube.com/c/TipsSindhi\nhttps://www.youtube.com/c/TipsKannada",
            "tags": [
                "ponniyin selvan",
                "ponniyin selvan songs",
                "ar rahman",
                "ps 1 song",
                "karthi ponniyin selvan",
                "ponni nadhi",
                "ponni nadhi song ponniyin selvan",
                "ponni nadhi song",
                "ponni nadhi ps1",
                "ps1 ponniyin selvan",
                "ps1 ponni nadhi song",
                "karthi ponni nadhi song",
                "ponniyin selvan ponni nadhi",
                "ponniyin selvan ponni nadhi song",
                "ps 1 songs tamil",
                "a r rahman tamil songs",
                "ponniyin selvan first single",
                "ponni nadhi full",
                "ponni nadhi full song",
                "ponni nadhi full video song tamil",
                "ponni nadhi full song video"
            ],
            "channelTitle": "Tips Tamil",
            "publishedAt": "2022-11-14T04:30:09Z"
        },
        {
            "id": "85c09a41-b7e4-424c-a54c-2be210307faa",
            "videoId": "eHSm5dAJbqg",
            "title": "MUJHE PYAAR HO GAYA HAIN: Sourav Joshi Vlogs, Pragati Verma | Saaj Bhatt, Sandeep Batraa | Love Song",
            "thumbnail": "https://i.ytimg.com/vi/eHSm5dAJbqg/maxresdefault.jpg",
            "duration": "PT4M3S",
            "description": "Voila! Digi presents 'Mujhe Pyaar Ho Gaya Hain', starring Sourav Joshi Vlogs & Pragati Verma and sung by Saaj Bhatt. This is a cute college love story, that every youngster will relate to. Relive your college love story through this song, and let us know your story in the comments below. #souravjoshivlogs #pragativerma #saajbhatt #souravjoshi  #voiladigi\n\nComment your favourite line from the song in the comment section. If you like the song, do leave a like and share the song with your friends and family. \n\nMake Reels: https://www.instagram.com/reels/audio/1184057609130906/\n\nMake YouTube shorts and Reels on the song and tag the 'Mujhe Pyaar Ho Gaya Hain' team. We would love to see your creativity and would even share the best ones! \n\n‘Mujhe Pyaar Ho Gaya Hain’ is available on all audio platforms:\nWynk Music: https://bit.ly/3O7OX5J\nSpotify: https://spoti.fi/3OeeGt5\nJioSaavn: https://bit.ly/3AjvzNd\nYouTube Music: https://bit.ly/3UuVcCR\nApple Music: https://apple.co/3tNPY9L\nAmazon Prime Music: https://amzn.to/3hB1wKl\n\nHear Sourav Joshi's other songs: https://youtube.com/playlist?list=PLosW0gUeNzwbs63b42ZmfIPxmvpAot6Ur\n\nHear Pragati Verma's other songs: https://youtube.com/playlist?list=PLosW0gUeNzwb7gxiHPzgyDHqTF742bN0U\n\nCredits:\nStarring: Sourav Joshi & Pragati Verma\nSinger: Saaj Bhatt\nMusic Composer: Sandeep Batraa\nLyricist: Azeem Shirazi\nProducers: Girish Jain & Vinit Jain\nSpecial Thanks: Karishma Chhajer\nDirector: Nitesh Tyagi\n\nVideo Credits:\nDOP: Rajveer Singh\nEdit: Nitesh Tyagi\nAD: Rudra Krishna\nDI: Prince Sethi\nLine Producer: Sanjay Bisht, Rajat Kumar, (TNL Event & Production)\nLocation: Tula's Institute Dehradun, Tula's International School\nSpecial Thanks: Discover Uttarakhand Magazine, Raunak Jain, Ashutosh Mishra, Rishabh Rautela\nFocus Puller: Suresh Dada\nMakeup: Ankush\nBTS: Manthan\n\nAudio Credits:\nElectric & Acoustic Guitar: Ishan Das\nTabla, Dholak & Percussion: Nitin Chimote, Prasad Mayekar\nBass Guitar: Ivan\nArrangement & Programming: Sandeep Batraa\nMixed & Mastered by: Prithvi Sharma at Soundvaultstudio\n\nOnline Promotions: Mediaone Network & Voila! Digi\nLabel: Voila! Digi\n\nWatch this love song and seed it in your New Hindi Songs 2022 playlist, romantic songs playlist, romantic song playlist, love songs playlist, romantic music playlist, love music playlist, romantic Hindi songs playlist, romantic hindi songs playlist, Hindi new songs playlist, hindi new song playlist, indian songs playlist, new song playlist, romantic hindi songs, hindi romantic songs playlist sourav joshi new song playlist, sourav joshi all songs playlist, sourav joshi songs playlist, sourav joshi song playlist, sourav joshi music video playlist, pragati verma song playlist, pragati verma songs playlist, pragati verma new song playlist, pragati verma music video playlist, saaj bhatt songs playlist, saaj bhatt new song playlist, saaj bhatt song playlist and all your other Hindi song and new songs playlists.\n\nFollow Voila! Digi:\nInstagram: https://www.instagram.com/voila_digi/...\nFacebook: https://www.facebook.com/voiladigi/\nTwitter: https://twitter.com/VoilaDigi\n\nSaaj Bhatt is exclusively managed by Voila! Digi. For any enquiries related to Saaj Bhatt:\nsaaj@voiladigi.in\n\nFor enquiries: contact@voiladigi.in",
            "tags": [
                "hindi new song",
                "hindi songs",
                "love songs",
                "mujhe pyaar ho gaya hai",
                "mujhe pyaar ho gaya hain",
                "new hindi song 2022",
                "new hindi songs",
                "pragati verma",
                "pragati verma music video",
                "pragati verma new song",
                "pragati verma new video",
                "pragati verma shorts",
                "pragati verma song",
                "roman"
            ],
            "channelTitle": "Voilà! Digi",
            "publishedAt": "2022-11-15T02:45:07Z"
        },
        {
            "id": "f1ecc1a4-3a77-432e-9d54-6fbfeac805ef",
            "videoId": "N-pvp7GSD3Y",
            "title": "Appatha Video Song | Naai Sekar Returns | Vadivelu | Suraaj | Santhosh Narayanan | Lyca Productions",
            "thumbnail": "https://i.ytimg.com/vi/N-pvp7GSD3Y/maxresdefault.jpg",
            "duration": "PT3M6S",
            "description": "#Vadivelu #naaisekarreturns #santhoshnarayanan #prabhudeva #Suraaj  #lycaproductions \n\nPresenting the video song #Appatha from the movie #NaaiSekarReturns \n\nCast – Vadivelu, Rao Ramesh, Anandraj, Munish Kanth, Reddin Kingsley, Sivaangi Krishnakumar, Shivani Narayanan, ‘Lollu Sabha’ Maaran, Manobala, ‘Lollu Sabha’ Seshu, TM Karthik, ‘KPY’ Ramar, ‘KPY’ Bala, Prashanth Rangaswamy\n\nMusic Credits :\nSong Name : Appatha \nSinger : 'Vaigaipuyal' Vadivel\nLyrics : Durai, Asal Kolar \nTrumpet : Vijay\nAdditional Vocals : ofRo, Durai\nComposed, Arranged and Programmed by Santhosh Narayanan\nAdditional Music Production : ofRo\nRecorded by Santhosh Naryanan\nRecorded at Future Tense Studios, Chennai\nRecording Engineer : Rupendar Venkatesh, Pranav Muniraj\nMixed and Mastered by Rupendar Venkatesh at Future Tense Studios\nMusicians Coordinator : Meenakshi Santhosh\n\nListen to #Appatha track from #NaaiSekarReturns on you favourite streaming apps:\n\nSpotify                : https://spoti.fi/3Gg5McC\nYouTube Music : https://bit.ly/3URaRw2\nApple Music      : https://apple.co/3UFGGZ1\nResso                 : https://bit.ly/3g2ey38\nHungama          : https://bit.ly/3ttnz8D\n\nMovie Credits :\nLyca Productions\nSubaskaran Presents ‘Vaigai Puyal’ Vadivelu in Naai Sekar Returns\n\nDirector - Suraj\nMusic - Santhosh Narayanan\nDOP - Vignesh Vasu S.I.C.A\nEditor - Selva RK\nArt Director - Umesh J Kumar\nLyricist - Vivek\nCo Director - S B Ramadoss\nAction - Hari Dinesh, Pradeep Dinesh\nSound Design & Sound Mix - T Udhayakumar (Knack Studios)\nCostume designs - Sher Ali\nCostumer - P Ganesh\nMakeup - Mariyappan\nDi - IGene\nColorist - Kannan\nVFX - Hariharasuthan\nPublicity Designs - Yuvaraj Ganesan\nPRO - Yuvaraaj / Sathish (aim)\nStills - T Arun Prasath\nDirection Team - Pradeep, P Vino Kumar, Santhosh\nManagers Team - Saattai N Shanmugam, Seithur K Elango\nProduction Controller - R S Venkat\nExecutive Producer - Subramanian Narayanan - M R Ravi\nHead of Lyca Productions - G.K.M. Tamil Kumaran\nProduced by Lyca Productions\n\n\nAudio Label : Think Music\n© 2022 SPI Music Pvt. Ltd.\n\nFor All Latest Updates:\nWebsite: https://thinkmusic.in/\nSubscribe to us on: http://www.youtube.com/thinkmusicindia\nFollow us on: https://twitter.com/thinkmusicindia\nLike us on: https://www.facebook.com/Thinkmusicofficial\nFollow us on: https://www.instagram.com/thinkmusicofficial",
            "tags": [],
            "channelTitle": "Think Music India",
            "publishedAt": "2022-11-14T13:30:10Z"
        },
        {
            "id": "a6435a1a-2ae5-4e13-b48c-85151d3848f3",
            "videoId": "UBOHA9a5NIQ",
            "title": "12 Ladke - Tony Kakkar , Neha Kakkar | Official Music Video",
            "thumbnail": "https://i.ytimg.com/vi/UBOHA9a5NIQ/maxresdefault.jpg",
            "duration": "PT2M23S",
            "description": "#12Ladke #tonykakkar  #nehakakkar \n\nSinger- Tony Kakkar , Neha Kakkar\nMusic - Tony Kakkar \nLyrics- Tony Kakkar \nMusic Produced & Mixed by Tony Kakkar \n\nDistribution Partner : Ingrooves \n\nVideo Credits \nDirected by Tony Kakkar, Sumit Kumar, Prathmesh Parab,  @Prathmesh Chaukekar \nVFX - Prathmesh Chaukekar, Prathmesh Parab\nChoreographed by Sumit Kumar\nD.O.P - Shinda Singh\nArt director : karma art studio\nColorist : Ercan kucuk\nAssistant director : Khush(robin)\nHair stylist : salman\nMake up : Rajan passi\nJimmy jib : gaurav\nProduction : RS Films & Production",
            "tags": [
                "tony kakkar",
                "neha kakkar",
                "tony kakkar new song",
                "neha kakkar new song",
                "tony kakkar song",
                "neha kakkar song",
                "12 ladke song",
                "12 ladke",
                "12 larke",
                "12 ladke saath ghoome",
                "tera boyfriend kaun sa",
                "party song 2022",
                "dance song 2022",
                "new song",
                "Viral Song",
                "Tony Kakar",
                "Latest Hits",
                "Latest song",
                "New Song",
                "Bollywood",
                "neha kakkar latest song",
                "trending",
                "bollywood viral song",
                "hits of neha kakkar",
                "blockbuster",
                "tony kakkar fans",
                "neha kakkar fans"
            ],
            "channelTitle": "Tony Kakkar",
            "publishedAt": "2022-11-14T03:33:23Z"
        },
        {
            "id": "e6788e82-6437-475f-8701-0b51e5ccce12",
            "videoId": "0N3FqawoavE",
            "title": "Munda Sardaran Da: Jordan Sandhu & Sweetaj Brar | Shree Brar | New Punjabi Song 2022",
            "thumbnail": "https://i.ytimg.com/vi/0N3FqawoavE/maxresdefault.jpg",
            "duration": "PT4M7S",
            "description": "Munda Sardaran Da | ਮੁੰਡਾ ਸਰਦਾਰਾਂ ਦਾ\n#MundaSardaraDa #JordanSandhu #ShreeBrar #SweetajBrar \n\nFateh Karan & Jordan Sandhu presents Official Video of Punjabi Song, Munda Sardaran Da by Jordan Sandhu featuring Sweetaj Brar and written by Shree Brar. \n\n🎵 Listen to Munda Sardaran Da on all audio stores:-\n\nSpotify: https://bfan.link/munda-sardaran-da/spotify\n\nApple Music: https://bfan.link/munda-sardaran-da/appleMusic\n\nWynk: https://bfan.link/munda-sardaran-da/wynk\n\nResso: https://bfan.link/munda-sardaran-da/resso\n\nAmazon: https://bfan.link/munda-sardaran-da/amazonMusic\n\nYouTube Music: https://bfan.link/munda-sardaran-da/youtubeMusic\n\nTrack Credits :-\nSong - Munda Sardaran Da\nSinger - Jordan Sandhu featuring Sweetaj Brar\nLyrics - Shree Brar\nMusic - Flamme Music\nDirector - Bhindder Burj \nDOP - Gagan Randhawa\nEditor - Jagjeet Singh Dhanoa\nColorist - Onkar Singh\nProducer - Fatehkaran Singh,Shree Brar\nAsst. Editor -Amrinder Singh\nProduction - Majha Production \nAsst. Director - Ammu Lahoriya/ Sarb Sandhu & Laala Gill\nAssociate Director - Pal Mahla\nOnline promotions - Digital Doctorz\n\nTeam Believe Artist Services:- https://linktr.ee/believeartistservicesindia\n\nEnjoy And Stay Connected With Artist || SHREE BRAR\n\nClick to Subscribe - https://www.youtube.com/channel/UCD0Hu-1xvkZ9ixaP8eUmbdQ\nInstagram - https://instagram.com/officialshreebrar\nFacebook - https://www.facebook.com/shreebraar\n\n For Licensing inquiries: \n Email:- sync-india@believedigital.com\n\n#JordanSandhu #ShreeBrar #lovesong #punjabisong #MundaSardaranDa",
            "tags": [
                "shree brar",
                "munda sardara da",
                "jordan sandhu",
                "sweetaj brar",
                "shree brar song",
                "shree brar songs",
                "shree brar new songs",
                "shree brar all songs",
                "shree brar munda sardara da",
                "jordan sandhu song",
                "jordan sandhu new songs",
                "jordan sandhu new song",
                "sweetaj brar song",
                "sweetaj brar new song",
                "sweetaj brar new songs",
                "shree brar new song",
                "new punjabi song",
                "new punajbi songs",
                "latest punjabi songs",
                "new punjabi song 2022",
                "latest punjabi songs 2022",
                "punjabi new song",
                "new punjabi songs 2022"
            ],
            "channelTitle": "Shree Brar",
            "publishedAt": "2022-11-14T04:30:04Z"
        },
        {
            "id": "2fa8f872-306f-4cc7-b528-4a334abe6a8a",
            "videoId": "g_GEWxi5Wfg",
            "title": "Aben Dona Juri kuri full video//Raju//Guddy//Jony//Punam//Mariam//2022//Santhali Traditional Song",
            "thumbnail": "https://i.ytimg.com/vi/g_GEWxi5Wfg/maxresdefault.jpg",
            "duration": "PT5M3S",
            "description": "Cast - Jony Mariam & Punam\nSinger - Raju Soren & Guddy Hembrom\nLyrics - Love Boy (Prem)\nDirector - Sudhir Hembrom\nManager - John Emmanuel Soren\nMusic - Cs Brother's\nChoreographer - Simon Murmu\nDancer - Simon & Rakesh\nCamera - Lucky Santosh\nAsst. Camera - Pradeep Murmu\nEdit & Cc - Ajit Tudu\n\nSpecial Thanks\nRavi Marandi,Pritam Hembrom, Abhishek Lal, Shailendra,Amit,Mary Murmu",
            "tags": [],
            "channelTitle": "Raju Soren",
            "publishedAt": "2022-11-15T02:30:08Z"
        },
        {
            "id": "f0dbf65b-061c-4f71-aa7a-dced3815e1ac",
            "videoId": "t_aO4EMP-i0",
            "title": "Gundellonaa - Video Song | Ori Devuda | Vishwak Sen, Asha | Ashwath Marimuthu | Leon James | Anirudh",
            "thumbnail": "https://i.ytimg.com/vi/t_aO4EMP-i0/maxresdefault.jpg",
            "duration": "PT4M1S",
            "description": "Here is the lovely \"Gundellonaa\" from 'Ori Devuda' ft. Vishwak Sen, Asha sung by Anirudh Ravichander, set to tunes by Leon James and penned by Kasarla Shyam. \n\nFor more latest songs and videos, subscribe now @Saregama Telugu  \n\nSong Credits:\nMusic - Leon James\nSinger - Anirudh Ravichander\nLyrics - Kasarla Shyam\n\nFlute - Kiran\nElectric Guitar - Keba Jeremiah\nPercussions - Krishna Kishor, Tapass Naresh, Ini, Imran\nSynths & Rhythm Production - Leon James\nMixed & Mastered by Rupendar Venkatesh \nMusic Manager - Roshan Doshi\n\nListen to \"Gundellonaa\" song on your favorite streaming platforms:-\nJioSaavn - https://tinyurl.com/mv7d6jt6\nSpotify - https://tinyurl.com/459skezv\nResso - https://m.resso.com/ZSRqEXjcL/\nHungama - https://tinyurl.com/ycf2u38f\nAmazon Music - https://tinyurl.com/5zcjk3t5\nYouTube Music - https://tinyurl.com/5e79a8uw\n\nMovie Details:-\nMovie - Ori Devuda / ఓరి దేవుడా \nStarring -  Venkatesh Dagubatti, Vishwak Sen, Mithila & Asha\nBanners - PVP Cinema & Sri Venkateswara Creations\nDirector & Writer - Ashwath Marimuthu\nProducers - Pearl V Potluri, Param V Potluri\nMusic - Leon James\nDOP - Vidhu Ayyanna\nDialogues - Tharun Bhascker\nChoreographer - Sathish Krishnan\nEditor- Vijay Mukthavarapu\nExecutive producer - Vamsi Kaka\nDigital Partner - Whackedout Media\n\nLyrics:\nPallavi:\n-------------\nIduvane iduvane kshanam kooda ninne\nBujjamma bujjamma\nMaruvane maruvane kalallonu  ninne\nBujjamma bujjamma\nGodavale padanule neetho godugu laa needouthaane\nAdugule vesthaanamma neetho arachethullo mosthune\n\nGundellonaa Gundellonaa ninnu daachesi\nGoode katti guvva lekka choosukuntaane\nGundellonaa Gundellonaa santhakam chesi\nPainoditho permission-ne thecchukunnaane\n\nRepeat Pallavi:\n-------------------------\nGadavane gadavadhe nuvve leni roje bujjamma bujjamma\nOduvane oduvade neepai naalo preme bujjamma bujjamma\n\nBGM:\n---------\nNaa Chinni Bujjamma...\nNaakannee Bujjamma...\n\nStanza:\n-----------\nKarigina kaalam thirigi thesthaane\nNimishamo guruthe isthaane bujjamma\nMigilina kathane kalipi raasthaane\nManakika dhooram undoddhe bujjamma\nManasulo thalichinaa chaale \nChitikelo neeke edhuravuthaane\nKanulatho adigi choode \nentho santhosham nimpesthaane...ne...ne...\n\nGundellonaa Gundellonaa ninnu daachesi\nGoode katti guvva lekka choosukuntaane\nGundellonaa Gundellonaa santhakam chesi\nPainoditho permission-ne thecchukunnaane\n\nEnding :\n------------\nGundelonaa...Gundelonaa...\nKottha range nimpukunna...\nGundelonaa...Gundelonaa...\nBomma needhe geesukunnaa...\nIduvane iduvane kshanam kooda ninne\nBujjamma bujjamma\n\nLabel: Saregama India Limited, A RPSG Group Company\n\nTo buy Carvaan, visit https://www.saregama.com/carvaan/telugu\nTo buy virus free original tracks, visit  https://www.saregama.com/musicstore\nFollow us on: YouTube:https://www.youtube.com/channel/saregamatelugu\nFacebook: http://www.facebook.com/Saregamatelugu\nTwitter: https://twitter.com/saregamasouth​​\n\n#Gundellonaa #OriDevuda  #VishwakSen #Asha #AnirudhRavichander #LeonJames #SaregamaTelugu",
            "tags": [
                "Gundellonaa",
                "Ori Devuda Movie Songs",
                "Ori Devuda Movie",
                "Vishwak Sen",
                "Mithila Palkar",
                "Ashwath Marimuthu",
                "Dil Raju",
                "Avunanavaa",
                "Anirudh telugu songs",
                "Anirudh ori devuda",
                "Vishwak Sen movies",
                "Leon James",
                "Latest Telugu Songs 2022",
                "Latest Telugu songs",
                "Telugu Hit songs",
                "Leon James Songs",
                "Anirudh Songs",
                "Kasarala Shyam",
                "taar maar thakkar maar",
                "kalaavathi",
                "sita ramam songs",
                "Gundellonaa video song",
                "gundelona gundelona song"
            ],
            "channelTitle": "Saregama Telugu",
            "publishedAt": "2022-11-13T05:35:10Z"
        },
        {
            "id": "e2096b68-432a-40e9-8f46-b2cb15c2f5c6",
            "videoId": "Qx3CDjkUISs",
            "title": "Chal Payi Chal Payi - Official Video | R Nait | Gurlez Akhtar | Gur Sidhu | Aveera | Bhinder Burj",
            "thumbnail": "https://i.ytimg.com/vi/Qx3CDjkUISs/maxresdefault.jpg",
            "duration": "PT3M36S",
            "description": "R Nait Music & Rajchet Sharma Presents Official Video of Punjabi Song Chal Payi Chal Payi by R Nait. The Song has been written by R Nait featuring Gurlez Akhtar and Music has been given by Gur Sidhu. \n\nListen to Chal Payi Chal Payi on all audio streaming platforms:-\n\n👉 Listen on Apple Music: https://rnait.bfan.link/chal-payi-chal-payi/appleMusic\n\n👉 Listen on Spotify: https://rnait.bfan.link/chal-payi-chal-payi/spotify\n\n👉 Listen on Wynk Music: https://rnait.bfan.link/chal-payi-chal-payi/wynk\n\n👉 Listen on Youtube Music: https://rnait.bfan.link/chal-payi-chal-payi/youtubeMusic\n\n👉 Listen on Resso App: https://rnait.bfan.link/chal-payi-chal-payi/resso\n\n\nTrack Credits:-\nSinger: R Nait, Gurlez Akhtar\nLyrics: R Nait\nMusic: Gur Sidhu\nMix & Master - B Sanjh\nFemale Lead: Aveera Singh Masson\nVideo: Bhindder Burj\nProject By: Satkaranvir Singh Khosa\nConceived by: Virvinder Singh Kaku\nPhotography: Jatinder Mehra\nPublicity Design: Impressive Design Studio\nOnline Promotion: Pro Media\n\nTeam Believe Artist Services:- https://linktr.ee/believeartistservicesindia\n\n\n🔔 Subscribe To Our Channel:   \n\n / R Nait - Topic:- https://www.youtube.com/channel/UC3fryLB2yC_5ImR9mEl1v-A  \n\nEnjoy & stay connected with us!\n► Like us on Facebook: https://www.facebook.com/OfficialRNait1\n► Follow us on Twitter: https://twitter.com/RNaitOfficial\n► Follow us on Instagram: https://instagram.com/official_rnait\n► Follow on Snapchat: https://www.snapchat.com/add/r-nait\n\nFor Licensing inquiries: \nEmail:- sync-india@believedigital.com\n\n#ChalPayiChalPayi #RNait #GurSidhu #gurlezakhtar  #NewPunjabiSong",
            "tags": [
                "r nait",
                "r nait all song",
                "r nait punjabi song",
                "punjabi gane",
                "r nait songs",
                "chal payi chal payi",
                "chal payi",
                "chal payi chal payi r nait",
                "chal payi song",
                "gur sidhu",
                "gurlez akhtar",
                "gurlez akhtar songs",
                "gur sidhu song",
                "punjabi song",
                "punjabi songs",
                "punjabi song 2022",
                "punjabi songs 2022",
                "punjabi song dj",
                "punjabi gane 2022",
                "r nait punjabi songs"
            ],
            "channelTitle": "R Nait",
            "publishedAt": "2022-11-15T04:31:01Z"
        },
        {
            "id": "f1e492f8-aa61-4de6-b1d7-f6897cc19531",
            "videoId": "KkFNTbGk_y0",
            "title": "RAFTAAR x BADSHAH -  RAASHAH (Explicit Warning) | Hard Drive Vol. 1 | Official Visualiser",
            "thumbnail": "https://i.ytimg.com/vi/KkFNTbGk_y0/maxresdefault.jpg",
            "duration": "PT3M53S",
            "description": "Special thanks to @Badshah bhaiya for #RaaShah\n\nArtists - RAFTAAR & BADSHAH\nTrack Name - RAASHAH\nWritten By - RAFTAAR & BADSHAH\nProduced By - YoungWilly\nMixed & Mastered By - ASHOCK (Bassholics)\nLabel - KALAMKAAR\n\n\nFollow RAFTAAR on Instagram - \nhttps://www.instagram.com/raftaarmusic/\n\nFollow BADSHAH on Instagram -\nBADSHAH - https://www.instagram.com/badboyshah/\n\n\n\n\n\n\n\n#Raashah  #badboyshah #raa #badshah  #raftaar  #HardDriveVol1 #indianhiphop #2022 #desihiphop #dhh #newmusic #epicsound",
            "tags": [
                "raftaar",
                "raftaar songs",
                "raftaar new song",
                "raftaar rap",
                "raftaar latest song",
                "kalamkaar"
            ],
            "channelTitle": "Raftaar",
            "publishedAt": "2022-11-15T18:41:31Z"
        },
        {
            "id": "c75135d7-7cdd-416a-9b78-2decc5f1a5bd",
            "videoId": "B4Am8BRJDos",
            "title": "RAFTAAR x KR$NA - NO CHINA (Explicit Warning) Hard Drive Vol. 1 | Official Visualizer",
            "thumbnail": "https://i.ytimg.com/vi/B4Am8BRJDos/maxresdefault.jpg",
            "duration": "PT3M30S",
            "description": "Special thanks to @KRSNA for No China\n\nArtists - RAFTAAR & KR$NA\nTrack Name - NO CHINA\nWritten By - RAFTAAR & KR$NA\nProduced By - RAFTAAR\nCo-Produced By - FRISK\nMixed & Mastered By - ASHOCK (Bassholics)\nLabel - KALAMKAAR\n\n\nFollow RAFTAAR on Instagram - \nhttps://www.instagram.com/raftaarmusic/\n\nFollow KR$NA on Instagram -\nKR$NA - https://www.instagram.com/realkrsna/\n\n\n\n\n\n\n\n#nochina #dollarsign  #raa #krsna  #raftaar  #HardDriveVol1 #indianhiphop #2022 #desihiphop #dhh #newmusic #epicsounds",
            "tags": [
                "raftaar",
                "raftaar songs",
                "raftaar new song",
                "raftaar rap",
                "raftaar latest song",
                "kalamkaar"
            ],
            "channelTitle": "Raftaar",
            "publishedAt": "2022-11-15T18:41:31Z"
        },
        {
            "id": "e96ebae3-30ba-4cef-9fec-b692dec4ff40",
            "videoId": "fafRQ8JJp3A",
            "title": "PEELE PEELE (Official Video) Khasa Aala Chahar | Khushi Baliyan | New Haryanvi Songs Haryanavi 2022",
            "thumbnail": "https://i.ytimg.com/vi/fafRQ8JJp3A/maxresdefault.jpg",
            "duration": "PT4M6S",
            "description": "PEELE PEELE (Official Video) Khasa Aala Chahar | Khushi Baliyan | New Haryanvi Songs Haryanavi 2022\n\nNav Haryanvi Presenting \"PEELE PEELE (Official Video)\" a New Haryanvi Songs Haryanavi 2022. Starring with Khasa Aala Chahar and Khushi Baliyan. Sung by Khasa Aala Chahar. Lyrics are panned by Khasa Aala Chahar and Music given by DJ Sky. Music Label by Nupur Audio.\n\n#peelepeele #khasaaalachahar #khushibaliyan  #navharyanvi #newharyanvisongsharyanavi2022 #haryanvi #haryanvisong #haryanvisongs #haryanvisongsharyanavi #haryanvigane #newharyanvisong #latestharyanvisong #hrsong\n\nSong - PEELE PEELE (Official Video)\nSinge/Lyrics/Composer - Khasa Aala Chahar\nMusic - DJ Sky\nMix Master - D Chandu\nFemale Lead - Khushi Baliyan\nVideo - Ameet Choudhary\nDop - Nishan Singh \nEdit/Di - Monty \nAD - Shoki & Navdeep Kukanda \nMakup - Mithun Da \nProduction - HS Dhaliwal \nChoreographer - Vinny Negi \nCostume - Rajjat Manchanda\nReels Promotion & Khushi Baliyan's Mangement - Diesel Entertainment\nDesign - Sumit Bamal\nProducer - Kshitij Gupta\nLabel - Nupur Audio\nPresenting Label - Nav Haryanvi\n\nOnline/Digital Promotion - Navi Baadliwal (9910117138)\n\nLOVE !! LIKE !! COMMENTS !! SUBSCRIBE\n\nDarling Peele Peele Re Song Lyrics -\nRe Koi Chod Ke Ja Jaave Sala Jaan De\nHawa Patli Gali Te Poori Aan De\nHo Teri Dil Ki Ek Dawai Aa\n Thare Gel Mila Ke Pee Le Re\nDarling Peele Peele Peele Peele Peele Re \nChhoti Si Zindagi Aa Jee Le Jee Le Jee Le Jee Le Jeele Re \n\nAa Naam Iska Sharab Reya Cheez  Na  Khrab\nDo Ghoont Mein Bna De Ya Saare Nwaab \nTere Sare Gam Ne Loot Levegi\nBin Soche Tu Peele Re\nDarling Peele Peele Peele Re \nChhoti Si Zindagi Aa Jee Le Jee Le Jeele Re \n\nO Reya Poori Wafadar Kade Deve Na Yah Dhokha\nMeri Maa Ne Or Dede Bete Sewa Ka Tu Mauka\nManne Khula Sher Bna Degi Tu Tutte Dil Ne Seele Re\n Darling Peele Peele Peele Peele Peele Re \nChhoti Si Zindagi Aa Jee Le Jee Le Jee Le Jee Le Jeele Re \n\nO Reya Khol Degi Raaj Ine Peele Tu Aaj \nKhasa Aala V Bjave Full Peeke Ne Saaj\nFer Khol Ke Burshat Nachega Tu \nTere Kurte Ho Ja Geele Re \nDarling Peele Peele Peele Peele Peele Re \nChhoti Si Zindagi Aa Jee Le Jee Le Jee Le Jee Le Jeele Re \n\nLabel & Copyright - Nupur Audio\nFor Song Releasing & Any query\nCompany Contact No. - +917042509060\nE-Mail ID : navharyanvi@gmail.com\nSubscribe Channel - https://www.youtube.com/c/NavHaryanvi\n\nConnect with Our Social Accounts\nSubscribe Our Channel on YouTube : https://goo.gl/hWsYba\nLike Us on Facebook : https://www.facebook.com/navharyanvi\nFollow Us on Instagram : https://www.instagram.com/navharyanvi\nTweet Us On : https://twitter.com/HaryanviNav\n\nPEELE PEELE (Official Video) Khasa Aala Chahar | Khushi Baliyan | New Haryanvi Songs Haryanavi 2022",
            "tags": [
                "peele peele",
                "peele peele song",
                "peele peele haryanvi",
                "peele peele khasa aala chahar",
                "peele peele khushi baliyan",
                "khasa aala",
                "khasa aala chahar",
                "khasa aala chahar song",
                "khasa aala chahar new song",
                "khushi baliyan",
                "new",
                "haryanvi",
                "songs",
                "haryanavi",
                "2022",
                "new haryanvi songs haryanavi 2022",
                "haryanvi song",
                "haryanvi songs",
                "haryanvi song 2022",
                "haryanvi songs 2022",
                "new haryanvi song",
                "new haryanvi song 2022",
                "latest haryanvi song 2022",
                "haryanvi dj song",
                "haryanvi songs haryanavi",
                "dj song 2022"
            ],
            "channelTitle": "Nav Haryanvi",
            "publishedAt": "2022-11-16T04:30:08Z"
        },
        {
            "id": "c5ac63b3-e39b-44f3-9289-985efe4912e9",
            "videoId": "jpYkoa-uE_c",
            "title": "Jehda Nasha: An Action Hero | Ayushmann, Nora Fatehi | Tanishk Faridkot Amar IP Singh Yohani Harjot",
            "thumbnail": "https://i.ytimg.com/vi/jpYkoa-uE_c/maxresdefault.jpg",
            "duration": "PT3M14S",
            "description": "Presenting the song \"Jehda Nasha\" sung by Amar Jalal, IP Singh, Yohani, Harjot Kaur. Recreated by Tanishk Bagchi and penned by Amar Jalal, Balla Jalal\n\n♪Full Song Available on♪ \nJioSaavn: http://bit.ly/3EDthLj\nSpotify: http://bit.ly/3ObJqem\nHungama: http://bit.ly/3hOxrr4\nApple Music: https://apple.co/3gaH6aO\nAmazon Prime Music: http://bit.ly/3GFgQQX\nWynk: http://bit.ly/3GoPYVc\nResso: http://bit.ly/3AndKwF\niTunes: https://apple.co/3tItOFv\nYouTube Music: http://bit.ly/3gaV8Jw\n\nSong Credits:\nSong: Jehda Nasha\nSingers: Amar Jalal, IP Singh, Yohani, Harjot Kaur\nMusic Recreated by: Tanishk Bagchi\nLyrics: Amar Jalal, Balla Jalal\nMix and Master: Eric Pillai @ Future Sound of Bombay\nMix Assistant Engineer: Michael Edwin Pillai\nMusic Label: T-Series\n\nYohani & IP Singh's Vocal recorded at T series studio. \nRecorded by Surajit Ghosh Mazumdar\n\nCast\nJedha Nasha: Nora Fatehi\nAyushmann Khurana\n\nProducer:  T-Series and Colour Yellow Production\nPresenter: BLM Studios\nDirector: Bosco Leslie Martis\nCreative Producer: Augustus Pereira\nExecutive Producer: Umesh Shinde\nProduction Designer: Prashant Rane\nDOP: Manoj Lobo\nEditor: Adele Pereira\n\nDirection Team\nAssociate Director: Augustus Pereira\nDirections Assistant: Vijay Singh\nAssistant Director: Saif Shaikh\n\nChoreographers\nAssistant: Ankan\nAlisha\nJack\nSahil\nParo\n\nProduction Team\nLine Producer: Chandrashekhar Nannaware\nUnit Production: Manager Raorane\nArtist Coordinator/ Production Manager: Amita Phatak\nProduction Manager: Hemant Dabholkar\nProduction Manager: Smit Mali\nProduction Manager: Virendra Patil\nLocation Manager: Pankaj Gamre\nLocal Manager: Yogesh Lokhande\n\nArt Team \nArt Director: Ketki Ghuge\nArt Assistant: Nilesh Morya\nDheeraj Sharma\n\n\nOriginal Credits\nSong Name: Nasha\nSingers: IP Singh, Amar Jalal\nMusic: Faridkot, Amar Jalal\nLyrics: Amar Jalal Group (Amar Jalal, Balla Jalal)\n\n___________________________________\nEnjoy & stay connected with us!\n👉 Subscribe to T-Series: http://bit.ly/TSeriesYouTube\n👉 Like us on Facebook: https://www.facebook.com/tseriesmusic\n👉 Follow us on Twitter: https://twitter.com/tseries\n👉 Follow us on Instagram: http://bit.ly/InstagramTseries",
            "tags": [
                "hindi songs 2022",
                "hindi songs new",
                "bollywood songs 2022",
                "bollywood movies 2022",
                "tseries",
                "tseries songs",
                "hindi songs",
                "bollywood romantic songs",
                "romantic hindi songs",
                "hindi songs bollywood",
                "remix hindi songs",
                "bollywood dance songs",
                "Amar Jalal",
                "IP Singh",
                "Yohani",
                "Harjot Kaur",
                "Ayushmann",
                "Nora",
                "Balla Jalal",
                "Jehda Nasha",
                "An Action Hero",
                "Jehda Nasha: An Action Hero",
                "Jehda Nasha Recreated",
                "Jeda Nasha",
                "NAsha",
                "Tera Nasha",
                "Jeda Nasha Nasha Teri",
                "Teri Ankha Vich",
                "official video"
            ],
            "channelTitle": "T-Series",
            "publishedAt": "2022-11-17T08:30:08Z"
        },
        {
            "id": "ea38d529-faea-4d1a-ae13-55123576caff",
            "videoId": "0ws4JuK5Lwg",
            "title": "MC STΔN - KAL HAI MERA SHOW (Official Video) | 2022 | INSAAN",
            "thumbnail": "https://i.ytimg.com/vi/0ws4JuK5Lwg/maxresdefault.jpg",
            "duration": "PT2M30S",
            "description": "Humanity was and will always be above all. Humans have started believing in illusions and live in their own worlds.\nThis album is the truth about insaan and various other elements of life which Stan has experienced and is expressing through this album.\n\n\n\" LIFE IS A TRIP UH KNOW MA SHITTT \"\n- MC STAN\n\n\nINSAAAAAAAAAAAAAAAAAAAN  !!!!!!\n\n              \nThe official audio for Mc Stan's \" KAL HAI MERA SHOW \" from his album ' INSAAN '\n!  Out Now  !\n\n\nStream ' INSAAN ' on all platforms: https://mcstan.bfan.link/insaan\n\nSpotify: https://open.spotify.com/album/5Xrj5h...\nApple Music: https://music.apple.com/in/album/insa...\nJioSaavn: https://www.jiosaavn.com/album/insaan...\nGaana: https://gaana.com/album/insaan-hindi-...\nAmazon: https://music.amazon.in/albums/B09SLN...\nResso: https://m.resso.com/ZSe7uq7KB/\nYoutube Music: https://music.youtube.com/playlist?li...\nHungama: https://www.hungama.com/album/insaan/...\n\n\nSinger / performer: MC Stan\nMusic Composer: MC Stan\nAuthor / Lyrics: MC Stan\n\nProd. by - MC STΔN\n\n\nFollow Mc Stan :\nINSTAGRAM -  https://www.instagram.com/m___c___stan/\nHINDI RECORDS - https://www.instagram.com/hindi_records/\n\n\nJinka Saboon slow hai woh saboon change karo pls ! PEACE OUT !\n\nFor Licensing enquiries: \nEmail:- sync-india@believedigital.com",
            "tags": [
                "mc stan",
                "kal hai mera show",
                "mc stan insaan album",
                "MC Stan",
                "stanny",
                "slatt",
                "slatt mc stan",
                "mc stan song",
                "mc stan songs",
                "mc stan rap",
                "hip hop",
                "mc stan all song",
                "desi hip hip",
                "dhh",
                "dhh rap",
                "kal hai mera show video",
                "insaan",
                "insaan mc stan",
                "kal hai mera show mc stan",
                "mc stan insaan",
                "insaan album",
                "MC stan",
                "hindi rap",
                "indian rap",
                "hindi rap song"
            ],
            "channelTitle": "MC STΔN",
            "publishedAt": "2022-11-18T11:30:10Z"
        },
        {
            "id": "fb15094e-117a-4c47-a8d7-44159129a606",
            "videoId": "rfF6vDzaPjs",
            "title": "Dil Jisse Zinda Hain | Nusrat Fateh Ali Khan |Gurmeet, Giorgia |Meet Bros,Jubin,Youngveer |Bhushan K",
            "thumbnail": "https://i.ytimg.com/vi/rfF6vDzaPjs/maxresdefault.jpg",
            "duration": "PT3M20S",
            "description": "Presenting the song \"Dil Jisse Zinda Hain\" sung by Meet Bros Feat. Jubin Nautiyal, music by Meet Bros penned by Youngveer\n\nGulshan Kumar & T-Series Presents\nBhushan Kumar's \n\"Dil Jisse  Zinda Hain\"\n\n♪Full Song Available on♪ \nJioSaavn: https://bit.ly/3geV4Zd\nSpotify: http://bit.ly/3AqhI7V\nHungama: https://bit.ly/3Gr1Y8o\nApple Music: https://apple.co/3tHdCoa\nAmazon Prime Music: https://amzn.to/3V24bLu\nWynk: http://bit.ly/3EIy5iH\niTunes: https://apple.co/3ge64pK\nYouTube Music: http://bit.ly/3TM9yh1\n\nSong Credits: \n\nSong: Dil Jisse  Zinda Hain \nMusic: Meet Bros\nSinger: Meet Bros Feat. Jubin Nautiyal\nLyrics: Youngveer\nIntro Alaap : Danish Sabri\nMusic Produced & Orchestrated By: Bharat Goel\nMusic arranger and Keys: Firoz Khan\nLive percussions arranged by: Raju Sardar\nChief Music Assistant and Music Production head: Uddipan sharma\nMusic Asst.: Piyush Mehroliyaa, Ankit Risaldar & Akash Ravi Chopra\nSong Recorded By: Gautam chakrabortty & Ankit Risaldar\nLive percussions recording supervised by: Sandeep Vishwa\nSong Recorded @ Meet Bros Recording Studio\nMixed & Mastered by: Bharat Goel @ Global Sound Labs B\nBusiness Head: Ketan Maniar\nMeet Bros Manager: Ruchir Saxena\nOperations Team: Nirja Bhatt, Aishawarya Mhatre & Karishma Meghani\nProduction Managed By: Suraj kumar\nFinance Team: Mayank Khandelwal, Feroz Khan, Anand Malpani & SMMP & Co\nMB Managing Director: Sunil Sajwani\n\nVideo Credits: \n\nVideo Director: Ivaan\nDOP: Sameer Arya \nEditor: Bunty Nagi\nCast: Gurmeet Chaudhary,Giorgia Andria-ni,Jaideep Singh,Raj Basu\nChoreographer: Rajitdev Easwardas\nArt Director: Dnyandeo Indulkar\nHead of Production: Mahipal Karan Rathore\n\nFirst Assistant Director: Avinash Nagtilak\n2ND Assistant Directors: Saniya Agrawal & Abhishek Singh\nChoreographer Assistant: Raveena Choudhary, Tejaswi Shetty, Rahul Sonawane, Bipin Kumar Srivastava \nDOP Associate: Srinivas Mandidi\nFocus Puller: Raj Kishore Kumar\n\n2ND DOP Assistant: Sandesh Patil \nAction Director: Moses Fernandes\nCostume Stylist: Subodh Srivastava\nAssociate Stylist: Harsh Kataria\nAssistant Stylist: Dolly Singh, Avinash Singh\nDancer’s Costumes: Khushboo Gupta\n \nGURMEET’S TEAM \nMakeup: Arvind Thakur\nHair: Firoz Saif\n \nGIORGIA’S TEAM \nMakeup: Monali Shah, Rajesh\nHair : Tabassum \n \nLine Producer: Naseem Shah\nProduction Executive: Lata Nand\nProduction Assistant: Jaseem Shabbir Shah\nProduction Runner: Mohd. Salim\nChartered Accountant: Nikunj Bagadi, Kumar Shriprakash\nAccountant: Akshay\nDI & VFX: PIXELLD Studio  \nColorist: RP\nOnline Editor: Nadeem Akhthar\nCamera  Equipment: Kshitij Entertainment Private Limited\nLight Equipment: Imperial Lights & Grips\nDisco Light Equipment: Light Craft & Sound Pvt Ltd\nSteadicam Equipment & Operator: Arbaaz Ansari\n \nTrack & Trolly Equipment: A.S. Enterprises\nGenny: M.J Power\nJimmy Jib: Star Cine Services\nPost Production: Rajan Pawar\nSFX: One Stop Film Solution Company\nArt Decor: Jain Decorators (Chirag Jain)\nLocations: Aayush Resort, Imperial Palace Resort\n\n:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n\nOriginal Credits \nSong Name: Dil Jis Se Zinda Hai\nAlbum Name: Supreme Collection, Vol.1 (Ustad Nusrat Fateh Ali Khan)\nSinger:  Ustad Nusrat Fateh Ali Khan\nLyricist: Zafar Ali Khan\nComposer: Ustad Nusrat Fateh Ali Khan & Mujahid Mubarak Ali Khan\nEMI Pakistan\n\n___________________________________\nEnjoy & stay connected with us!\n👉 Subscribe to T-Series: http://bit.ly/TSeriesYouTube\n👉 Like us on Facebook: https://www.facebook.com/tseriesmusic\n👉 Follow us on Twitter: https://twitter.com/tseries\n👉 Follow us on Instagram: http://bit.ly/InstagramTseries",
            "tags": [
                "hindi songs 2022",
                "hindi songs new",
                "tseries",
                "tseries songs",
                "hindi songs",
                "bollywood dance songs",
                "Gurmeet Choudhary",
                "Giorgia Andriani",
                "Gurmeet",
                "Meet Bros",
                "Jubin Nautiyal",
                "Youngveer",
                "Bhushan Kumar",
                "Dil Jisse Zinda hain",
                "Nusrat Fateh Ali Khan",
                "Dil Jisse Zinda hai Nusrat Fateh Ali Khan",
                "Dil Jisse Zinda hai Jubin Nautiyal",
                "Dil Jisse Zinda hai",
                "Dil Jisse Zinda hain By Jubin Nautiyal",
                "New Song",
                "Song 2022",
                "Hit Song",
                "Hindi Hit Song",
                "Dance Song",
                "Dil Jisse",
                "Dil Jisse By Nusrat"
            ],
            "channelTitle": "T-Series",
            "publishedAt": "2022-11-18T05:30:07Z"
        },
        {
            "id": "f93f9aa7-f739-4beb-b22b-4b5c51ca1ac2",
            "videoId": "vjgVVYIip90",
            "title": "Naazneen | Bhoomi 2022 | GoDaddy India | Raj Pandit, Noor Mohammad | Salim Sulaiman | Kashmir Songs",
            "thumbnail": "https://i.ytimg.com/vi/vjgVVYIip90/hqdefault.jpg",
            "duration": "PT5M51S",
            "description": "#Naazneen brings colours of Kashmiri folk in the voices of Raj Pandit and Noor Mohammad. Featuring modern synths and drums fused with traditional folk instruments, the song is composed and produced by Salim - Sulaiman and Ghulam Nabi Doolwal. \n\nPenned by Lalleshwari, Ghulam Nabi Doolwal and Aditya Kalway, the song traces the journey of life, from a person's wedding to someone else's cremation.\n\nThis track is a collaboration between #RajPandit, Noor Mohammad and #SalimSulaiman in GoDaddy presents Bhoomi 2022, powered by Moha and Adda52.\n\nBhoomi started 20 years ago, and it follows the successful grand chapter of Bhoomi 2021. Salim-Sulaiman bring together more than 25 different musicians across India bringing authenticity to the musical influences in styles, melodies and lyrics across our own ‘Bhoomi.’\n\nSubscribe to our channel for more music everyday 🔔\n\nTo SUBSCRIBE click the link below:\nhttp://www.youtube.com/subscription_center?add_user=SalimSulaimanMusic\n\nAudio Credits –\n‘Naazneen’ Originally Composed & Written by: Ghulam Nabi Doolwal \nLal Vaakh Written by: Lalleshwari (Lal Ded)\nMusic Composed & Produced by: Salim Sulaiman \nHindi Lyrics: Aditya Kalway\nSingers: Raj Pandit, Noor Mohammad\nMusic Co-Produced by: Raj Pandit\n\nDrums: Darshan Doshi\nGuitars: Nyzel D’lima, Muheet Bharti\nRabab: Tapas Roy\nTumbaknari: Sulaiman Merchant\nPiano & Keyboard: Jarvis Menezes\nBass: Rushad Mistry\nBacking Vocals: Rajiv Sundaresan, Muheet Bharti, Aditya Kalway, Suhas Sawant, Yashika Sikka, Darshana Menon, Umesh Joshi, Janardan Dhatrak, Aditi Prabhudesai, Dattatray Mestri, Deepti Rege, Archana Gore\nRecorded by: Aftab Khan, Raj Pandit & Muheet Bharti at Blue Productions \nDrums Recorded by: Adithya Sivakumar at Island City Studio\nMixed & Mastered by: Aftab Khan at Headroom Studio\nMix Assistant: Vatsal Chevli\nDistributed by: Global Music Junction, Warner Music India\nSpecial Thanks to : Neerja Pandit, Baba Tassaduq Hussain\n\nDirector: Shakti Hasija\nProject Head: Nirav Thakar\nArtist Relations: Radhika Mistry\nPartnerships, Strategy and Marketing: Shivansh Jindal\n\nLine Production: Ashoke Pandit Productions \nAssociate Producer: Rajveer Ahuja\n\nSet Design: The Concert Production \nProduction Head: Zeeshan Siddiqui \nLight Designer: Sohail Mansuri \nLight Programer: Maaz Mansuri \nLed Graphics: Make Believe \nStage Manager: Prasad Satam \nTechnical Head: Rahul Thul\nProduction Assistant: Rahul Nirmal\nPromotional Packaging: Rahul Singh Somvanshi\n\nExecutive Video Producer: Kunjan Hasija\nLine Producer: Nidhi Oza\nDOP: Ravi \nChief AD: Jeetu Rall\nAssistant Director: Dev Byas\n\nPost Production: Industrywalas\nIndustrywalas Team\nEdit & Grading: Jeetu Rall\nAssociate Editor: Sushil Gothankar\nDIT & Assistant Editor: Prathmesh Kamerkar\n\nDOP Team\nDOP Asst.: Prashant Sati\nDOP Asst.: Parag\nCamera Operators: Prakash Simwal, Sabyasachi Das, Digant Gautam, Rajesh Kashyap, Prasad Talekar\nFocus Pullers: Vishnu Sharma, Kunal Mehra, Rahul Tripathi, Fuleshwar Pandit, Vinod Raj Kishore\n\nMakeup and Hair Designer: Suman Singh\nMakeup and Hair Team: Zabi Shaikh, Sunil Singh, Ankit Khasia, Jeetu Kumar, Sandeep Kumar, Rami Haldar, Jiya Jadhav\n\nFashion Director: Kavita Lakhani \nFashion Stylist: Priyal Pawan\nOutfit for Salim Merchant by Sahil Qureshi \nOutfit for Sulaiman Merchant by Vivek Gupta \nJewellery for Sulaiman Merchant by Giti Jewllery \nJewellery for Raj Pandit by Curio Cottage\n\nFinance Head (Blue Production): Anil Kajrolkar\nStills: Vishal Sain, Sanket B, Aakib Siddique\nAlbum Creatives: Dishant Mistry\nPR: Lily Ahluwalia\n\n#RajPandit #NoorMohammad #Naazneen #Kashmir #KashmiriFolk #Bhoomi22 #SalimSulaiman #Bhoomi2022 #GoDaddy #TheMohaLife #Adda52 #MerchantRecords\n\n\nTo SUBSCRIBE click the link below:\nhttp://www.youtube.com/subscription_center?add_user=SalimSulaimanMusic\n\nLike us on Facebook:\nhttps://www.facebook.com/salimsulaimanmusic\n\nFollow us on Twitter:\nhttps://twitter.com/SlimSulaiman\n\nFollow Salim Merchant on:\n\nTwitter: https://twitter.com/salim_merchant/\n\nInstagram: https://www.instagram.com/salimmerchant/\n\nFollow Sulaiman Merchant on:\n\nTwitter: https://twitter.com/Sulaiman\n\nInstagram: https://www.instagram.com/sulaiman.merchant/\n\nFollow Merchant Records on:\n\nFacebook: https://www.facebook.com/MerchantRecordsMusic\n\nInstagram: https://www.instagram.com/merchant_records/\n\nTwitter: https://twitter.com/MerchantRec",
            "tags": [
                "salim sulaiman",
                "salim",
                "sulaiman",
                "salim sulaiman songs",
                "live performance",
                "salim merchant",
                "sulaiman merchant",
                "merchant",
                "merchant records",
                "hindi songs",
                "new hindi songs",
                "kashmir songs",
                "raj pandit",
                "naazneen",
                "noor mohammad",
                "kashmir salim sulaiman",
                "lalleshwari",
                "nazneen",
                "raj pandit bhoomi 22",
                "ghulam nabi doolwal",
                "gulam nabi",
                "Naazneen yaar myaani",
                "kashmir folk songs",
                "indian folk music",
                "janbaz",
                "neerja pandit",
                "noor muhammad",
                "singers of kashmir",
                "sufiyana",
                "sufi",
                "nazneen yaar maine",
                "naznin yaar"
            ],
            "channelTitle": "Salim Sulaiman",
            "publishedAt": "2022-11-18T11:00:08Z"
        },
        {
            "id": "fe7b3d1a-a6f4-49b7-ab1c-07dd28ef363c",
            "videoId": "xh_4jogs4zM",
            "title": "HAZUR (Official Video) Arjan Dhillon | Mxrci | Latest Punjabi Song @Brown Studios",
            "thumbnail": "https://i.ytimg.com/vi/xh_4jogs4zM/maxresdefault.jpg",
            "duration": "PT2M43S",
            "description": "Brown Studios & Harwinder Sidhu Presents :\n\nSong - Hazur\nSinger/Lyrics/Composer - Arjan Dhillon\nMusic - Mxrci\nVideo - I Can Films\nOnline Promotions - Gold Media Entertainment\nArtwork - The Town Media\nProducer - Harwinder Sidhu\n\nLabel - Brown Studios",
            "tags": [
                "new punjabi songs 2022",
                "new punjabi music",
                "new punjabi song",
                "new punjabi song 2022",
                "new punjabi song 2021",
                "new punjabi song latest this week",
                "latest punjabi songs 2022",
                "new songs",
                "latest songs",
                "punjabi song 2022",
                "latest punjabi songs",
                "new latest punjabi songs 2022",
                "all new punjabi songs latest",
                "Hit punjabi songs 2022",
                "new punjabi songs 2021 latest this week",
                "top 10 punjabi songs",
                "hazur",
                "arjan",
                "dhillon",
                "arjan dhillon",
                "mxrci"
            ],
            "channelTitle": "Brown Studios",
            "publishedAt": "2022-11-18T13:30:11Z"
        },
        {
            "id": "9fb699fb-6e6f-4e48-b670-91abc34434c9",
            "videoId": "yX8ZqaXTTfk",
            "title": "Tum Jo Milo | Freddy | Kartik Aaryan, Alaya F | Pritam | Abhijeet Srivastava | Irshad Kamil",
            "thumbnail": "https://i.ytimg.com/vi/yX8ZqaXTTfk/maxresdefault.jpg",
            "duration": "PT3M1S",
            "description": "Watch This Love Song Of Kartik Aaryan & Alaya F “Tum Jo Milo” From the Latest Upcoming Hindi Movie 'Freddy', Music Composed By Pritam, Vocal By Abhijeet Srivastava, Lyrics Are Penned by Irshad Kamil.\n\nStay updated with the latest videos from Tips Official, Subscribe on the below link.\nhttp://youtube.com/tipsofficial\n\nSong Details :\nSong Name: Tum Jo Milo\nMusic - Pritam\nLyrics - Irshad Kamil\nSinger - Abhijeet Srivastava\n\nEnglish Singer - Shreya Phukan\nEnglish Lyrics - Shreya Phukan & Brianna Supriyo\n\nMusic Arranger and Programmer - Himonshu Parikh\nSound Design - DJ Phukan & Ashwin Kulkarni\nMix & Master - Shadab Rayeen at New Edge\nChief Engineer & Shootmix - Ashwin Kulkarni\nMusic Production Manager - Anurag Sharma\n\nSound Engineers - Aniruddh Anantha & Pranav Gupta\nVocal Conductors - Aniruddh Anantha, Dev Arijit & Antara Mitra\nBacking Vocal Design & Performed - Aniruddh Anantha\nMixing Assistant to Shadab – Pukhraj Sonkar and Anup Gandharla\nAssistant to Himonshu - Shirish Prakash Singh\n\nMovie Details : \nPresented By: Disney+ Hotstar \nBanner : Balaji Telefilms Ltd., NH Studioz & Northern Lights Films\nStar Cast: Kartik Aaryan, Jeniffer Piccinato, Alaya F\nProduced By Ektaa R Kapoor, Shobha Kapoor, Narendra Hirawat, Shreyans Hirawat & Jay Shewakramani\nDirected By Shashanka Ghosh\nDirector of Choreography - Piyush-Shazia\nSong Editor - Rishabh Shetty\nOnline artist- Dikshish mistry\nPost supervisor - Prabhat N Iyer\nRoto & Comp - Randhir Verma\n\n#freddy #pritam #KartikAaryan #alaya  #tumjomilo #HindiSong #newhindisong #newhindisongs  #bollywoodsongs #hindisongs #bollywoodhits #lovesongs #bollywoodhits #AbhijeetSrivastava #IrshadKamil\n\nIf you like the video don't forget to Like, Comment, and Share with others.\nStay connected with us!!!\nFollow us on our Social Media Platforms:\n► Facebook: https://www.facebook.com/TipsMusic\n► Instagram: https://www.instagram.com/tips\n► Twitter: https://twitter.com/tipsofficial\n\nJoin Us On:\nhttps://www.youtube.com/c/tipsofficial\nhttps://www.youtube.com/c/jhankargaane\nhttps://www.youtube.com/c/90sGaane\nhttps://www.youtube.com/c/TipsFilms\nhttps://www.youtube.com/c/TipsPunjabi\nhttps://www.youtube.com/c/TipsBhojpuri\nhttps://www.youtube.com/c/TipsMarathi\nhttps://www.youtube.com/c/bhaktiprem\nhttps://www.youtube.com/c/volume\nhttps://www.youtube.com/c/TipsRajasthani\nhttps://www.youtube.com/c/TipsHaryanvi\nhttps://www.youtube.com/c/TipsIbadat\nhttps://www.youtube.com/c/TipsTamil\nhttps://www.youtube.com/c/TipsGujarati\nhttps://www.youtube.com/c/TipsTelugu\nhttps://www.youtube.com/c/TipsMalayalamOfficial\nhttps://www.youtube.com/c/TipsSindhi\nhttps://www.youtube.com/c/TipsKannada",
            "tags": [
                "kartik aaryan",
                "tum jo milo video song",
                "tum jo milo song",
                "freddy",
                "freddy tum jo milo song",
                "kartik aaryan freddy",
                "kartik aaryan song",
                "Pritam",
                "freddy kartik aaryan",
                "freddy song",
                "kala jadu",
                "kala jadu song",
                "hindi new song",
                "kartik aaryan kala jadu song",
                "freddy movie song",
                "freddy movie kartik aryan",
                "alaya f",
                "kartik aryan new song",
                "kartik aaryan alaya f",
                "tips official songs",
                "pritam songs",
                "abhijeet srivastava song",
                "abhijeet srivastava new song",
                "abhijeet srivastava freddy song"
            ],
            "channelTitle": "Tips Official",
            "publishedAt": "2022-11-21T10:02:41Z"
        },
        {
            "id": "efecb463-52f6-4d7c-91cb-1f1dc61139d0",
            "videoId": "jEdfjuG0Fx4",
            "title": "정국 (Jung Kook) 'Dreamers' @ FIFA World Cup Qatar 2022 Opening Ceremony",
            "thumbnail": "https://i.ytimg.com/vi/jEdfjuG0Fx4/maxresdefault.jpg",
            "duration": "PT5M5S",
            "description": "Connect with BTS: \nhttps://ibighit.com/bts \nhttp://twitter.com/BTS_bighit\nhttp://twitter.com/BTS_twt \nhttp://www.facebook.com/bangtan.official \nhttps://www.youtube.com/user/BANGTANTV \nhttp://instagram.com/BTS.bighitofficial \nhttps://channels.vlive.tv/FE619 \nhttps://www.tiktok.com/@bts_official_bighit\nhttps://weverse.onelink.me/qt3S/94808190\nhttps://www.weibo.com/BTSbighit\nhttps://www.weibo.com/BTSmembers \nhttp://btsblog.ibighit.com",
            "tags": [
                "방탄소년단",
                "BTS",
                "BANGTAN",
                "알엠",
                "RM",
                "슈가",
                "SUGA",
                "제이홉",
                "jhope",
                "지민",
                "정국",
                "k-pop",
                "방탄",
                "j-hope",
                "Jung Kook",
                "Jimin",
                "BTS V",
                "Jin"
            ],
            "channelTitle": "BANGTANTV",
            "publishedAt": "2022-11-21T15:00:02Z"
        },
        {
            "id": "e9636336-a793-4e96-bbfc-385573c4a089",
            "videoId": "P36L0ApcyzU",
            "title": "Waltair Veerayya - Boss Party Song Promo | Megastar Chiranjeevi | Devi Sri Prasad | Bobby Kolli",
            "thumbnail": "https://i.ytimg.com/vi/P36L0ApcyzU/maxresdefault.jpg",
            "duration": "PT34S",
            "description": "BOSS PARTY\nSinger: Nakash Aziz, DSP & Haripriya \nLyrics: DSP\nKeyboards: Vikas Badisa \nRhythm: Kalyan \nChorus: S.P. Abhishek\nAlbum Mixed & Mastered by A. Uday Kumar @ “DSP Studio – Chennai” \nAlbum Recorded by A. Uday Kumar, T. Uday Kumar & Suresh Kumar Taddi.\nVocal Supervision: Orchestra In-Charge: Murugan\nStudio Asst: Pugalendhi, Dhinakaran & Bharat \nAlbum Co-ordinator: B.Manikandan\n\nMovie Details : \nMovie Name : Waltair Veerayya \nCast: Chiranjeevi, Ravi Teja, Shruti Haasan,Catherine Tresa\n\nTechnical Crew:\nStory, Dialogues, Direction: KS Ravindra (BobbyKolli)\nProducers: Naveen Yerneni and Y Ravi Shankar\nBanner: Mythri Movie Makers\nCEO: Cherry\nMusic Director: Devi Sri Prasad\nDOP: Arthur A Wilson\nEditor: Niranjan Devaramane\nProduction Designer: AS Prakash\nFights -Ram -Lakshman\nCostume Designer: Sushmita Konidela\nCo-Producers: GK Mohan\nScreenplay: Kona Venkat, K Chakravarthy Reddy\nAdditional Writing: Hari Mohana Krishna, Vineeth Potluri\nMarketing : First Show\n\nLine Producer: Balasubramanyam KVV\nProduction controller - Nagu Y\nPRO: Vamsi-Shekar\nPublicity: Baba Sai Kumar\nDI - Annapurna Studios \nColorist - Vivekanand \n\nMusic Label - Sony Music Entertainment India Pvt. Ltd.\n\n© 2022 Sony Music Entertainment India Pvt. Ltd.\n\nSubscribe Now: http://bit.ly/SonyMusicSouthVevo\nSubscribe Now: http://bit.ly/SonyMusicSouthYT\nFollow us: https://www.instagram.com/sonymusic_south/\nFollow us: Twitter: https://twitter.com/SonyMusicSouth\nLike us: Facebook: https://www.facebook.com/SonyMusicSouth",
            "tags": [
                "Sony Music South",
                "Sony Music",
                "Latest Song",
                "Tamil song",
                "Tamil Latest Song",
                "Tamil Latest Songs 2020",
                "Tamil Latest Songs 2021",
                "Latest songs in Tamil",
                "Songs in Tamil",
                "Latest Tamil Movies",
                "Tamil Movie Songs",
                "Latest Video Songs Tamil",
                "latest Tamil Love Songs",
                "Latest Tamil Hit Songs",
                "Telugu Songs 2021",
                "New Tamil Songs",
                "Songs in Telugu",
                "Telugu Movie Songs",
                "Video Songs Telugu",
                "new Telugu Songs"
            ],
            "channelTitle": "Sony Music South",
            "publishedAt": "2022-11-22T05:05:06Z"
        },
        {
            "id": "fc43efdb-09cf-45e6-bcbd-0f5b62c4cefd",
            "videoId": "nsMhMQfD0V0",
            "title": "Waltair Veerayya - Boss Party Lyric Video | Megastar Chiranjeevi, Urvashi Rautela | DSP, Bobby Kolli",
            "thumbnail": "https://i.ytimg.com/vi/nsMhMQfD0V0/maxresdefault.jpg",
            "duration": "PT3M19S",
            "description": "BOSS PARTY\nSinger: Nakash Aziz, DSP & Haripriya \nLyrics: DSP\nChoreography : VJ Sekhar Master\n\nMusician credits \nKeyboards: Vikas Badisa \nRhythm: Kalyan \nChorus: S.P. Abhishek\nAlbum Mixed & Mastered by A. Uday Kumar @ “DSP Studio – Chennai” \nAlbum Recorded by A. Uday Kumar, T. Uday Kumar & Suresh Kumar Taddi.\nVocal Supervision: Orchestra In-Charge: Murugan\nStudio Asst: Pugalendhi, Dhinakaran & Bharat \nAlbum Co-ordinator: B.Manikandan\n\nMovie Details : \nMovie Name : Waltair Veerayya \nCast: Chiranjeevi, Ravi Teja, Shruti Haasan,Catherine Tresa\n\nTechnical Crew:\nProducers : Naveen Yerneni, Y Ravi Shankar Co Producer : G.K Mohan Story-Dialogues-Direction : Bobby Kolli\nDop : Arthur A Wilson\nMusic : Devi Sri Prasad\nProduction Designer : A S Prakash\nScreenplay : Kona Venkat, K Chakravarthy\nAdditional Screenplay : Hari Mohana Krishna, Vineeth Potluri Additional Dialogues : Bhanu-Nandu\nEditor : Niranjan Devaramane\nCostume Designer - Krishna Santhi\nStunts : Ram-Laxman, Peter Hein\nCeo : Cherry\nChief Co-Directors : P V V Somaraju (Appaji)\nPoosala Radhakrishna\nCo-Director : V Kranthi Chakravarthi\nCostume Designers : Sushmita Konidela ,Neeraja Kona, Krishna Santhi, Sharsha\nPro : Vamsi-Sekhar\nPublicity Designer : Tuney John\nExecutive Producer : Bala Subramanyam K.V.V\nProduction Controller : Nagu Y\nVfx : Knack Studios\nStills : Guna\nMake Up : Siva, Srinu\nPRO : Vamsi-Sekhar\nMarketing : First Show\n\nMusic Label - Sony Music Entertainment India Pvt. Ltd.\n\n© 2022 Sony Music Entertainment India Pvt. Ltd.\n\nSubscribe Now: http://bit.ly/SonyMusicSouthVevo\nSubscribe Now: http://bit.ly/SonyMusicSouthYT\nFollow us: https://www.instagram.com/sonymusic_south/\nFollow us: Twitter: https://twitter.com/SonyMusicSouth\nLike us: Facebook: https://www.facebook.com/SonyMusicSouth",
            "tags": [
                "Sony Music South",
                "Sony Music",
                "Latest Song",
                "Telugu Songs 2021",
                "Songs in Telugu",
                "Telugu Movie Songs",
                "Video Songs Telugu",
                "new Telugu Songs",
                "Waltair Veerayya Tittle Teaser",
                "Megastar Chiranjeevi",
                "DSP",
                "Devi Sri Prasad",
                "Megastar 154",
                "Devi Sri Prasad songs",
                "KS Ravindra",
                "Chiranjeevi Movies",
                "MegastarMovies",
                "Mega154",
                "Mega 154 Muhurtham",
                "Megastar movies",
                "Bobby Movies",
                "Megastar Chiranjeevi Pooja Cermony Shots",
                "Dsp Latest songs",
                "Megastar",
                "#MegaMass",
                "#MegaMassComboBegins",
                "boss party song"
            ],
            "channelTitle": "Sony Music South",
            "publishedAt": "2022-11-23T10:35:03Z"
        },
        {
            "id": "df45ead2-457c-408f-87b2-2fd3ed266c95",
            "videoId": "7CBzfyMq64U",
            "title": "#Video | #Khesari Lal Yadav New Song | हसीना | #Anupama Yadav | #Yamini Singh | Haseena",
            "thumbnail": "https://i.ytimg.com/vi/7CBzfyMq64U/maxresdefault.jpg",
            "duration": "PT4M8S",
            "description": "लो भईया, है शादियों का महीना और #Khesari ले आये है अपना नया गाना \"हसीना\" तो नाचो ऐसा की ठण्ड में भी छूट जाये पसीना ....\n\nख़रीदिए कारवाँ मोबाइल- 1500 प्रीलोडिड गानों वाला कीपैड फ़ोन धमाकेदार साउंड के साथ\nhttp://sarega.ma/ycmbuy\n\nCredits:-\n\nSong Title - Haseena\n🎤 Singer - Khesari Lal Yadav & Anupma Yadav\n💃🏻 Feat - Yamini Singh\n✍ Writer - Chhotu Yadav\n🎼 Music - Vicky Vox\n🎼 Composition - Shubham Tiwari\n🎥 Video By - Team Sanju\n🎥 EP - Sitosh Yadav\n💃🏻 Director & Choregrapher - Geeta Tamta (ZENITH)\n💃🏻 Assistant choreographer- Japneet\n✂️ Edit - P. Shubham Babu\n🎥 DOP - Yogesh Singh\n🎥 DI - Rohit Singh\n👗 Yamini dress - ZAI FASHION (REEMA)\n🎥 Production - Abhay Pandey\n🎥 Assistant Production - Amit & Kamlesh\n\nLyrics :-\n\nMukhda\nM-Maina samaina me aail deewana\nGodie me kud ja tu kara na mana\nF- Suna Ho Kahile Nache Se Pahile, Tani Money Dala Hamara Tina Me\nM- Lage Dil Na Ba Ae Haseena Tohara Sina Me\n\nAntra - 1\n\nF-Adakara hai, dher udaba ta lut leb\nChai me dubawe khatir Tohase Biscuit Leb\nM- Chamakata Darling Deess Lagataru Chamakili,\nBaadu tu jatane jawan ohse jyada jahreeli\nF- Phonwa nikala Google me Dala\nBadi kadaki Chalata eh mahina me\nM- Lage Dil Na ba.....\nAntra -2\n\nF- Dher Bana Jani Ae Babu Tuhu Chalak Ho,\nKetna Log ke dekhale baani Marat dialouge ho\nM- Hili je hamar dimag kare lagab hungama,\nManabu na jadi kadi kareja khesari karnama\nF- Chhotu Shubhamawa Sanjay Ke Sanghawa\nBhijaiba Ka Dehiya Pasina Me\nM- Lage Dil Na Ba...\n\n#Khesari Lal Yadav & Anupama  के बवाल गाने सुनने के लिए आज ही Subscribe करे \nhttps://bit.ly/Saregamahumbhojpuri \n\n#Haseena \n#khesari  \n#khesarilalyadav \n#khesarilal  \n#aunpamayadav\n#bhojpuri \n#bhojpurisong \n#bhojpurigana \n\nSubscribe to our channel for more Bhojpuri Songs:\nhttps://youtube.com/c/SaregamaHumBhojpuri\n\nFollow us on:\nFacebook: https://bit.ly/3FxwPgo \nInstagram: https://bit.ly/32rkJqM\nTwitter: @saregamaglobal \n\nContact for Movie and Album \nBadrinath.jha@rpsg.in\n\nLabel:: Saregama India Limited, A RPSG Group Company",
            "tags": [
                "Haseena",
                "हसीना",
                "Khesari Lal Yadav",
                "Khesari Lal",
                "khesari lal new song",
                "khesari lal song",
                "khesari lal ke gana",
                "khesari lal new song 2022",
                "Bhojpuri Song",
                "anupma yadav",
                "anupama yadav new song",
                "tabla",
                "nathuniya",
                "apni toh jaise taise",
                "le le aayi coca cola",
                "sajke sawarke",
                "paro",
                "bas kar pagli",
                "aa jaihe 5 ke",
                "le la pudina",
                "hari hari odhani",
                "nachaniya karan",
                "pagal banaibe",
                "बात पायल के पता न चले",
                "हरी हरी ओढ़नी",
                "नचनिया कारन",
                "कमरिया पे भाला चली",
                "jhagda ke ghar",
                "pudina ae haseena"
            ],
            "channelTitle": "Saregama Hum Bhojpuri",
            "publishedAt": "2022-11-24T01:30:10Z"
        },
        {
            "id": "f9a1fcd1-3293-4f12-99a2-3fe2a2945b56",
            "videoId": "pVBmn5uJNKE",
            "title": "Bijli | Govinda Naam Mera | Vicky Kaushal, Kiara Advani |Sachin-Jigar, Mika Singh, Neha Kakkar, Vayu",
            "thumbnail": "https://i.ytimg.com/vi/pVBmn5uJNKE/maxresdefault.jpg",
            "duration": "PT2M58S",
            "description": "Current maare Bijli!\n\nPresenting the most electrifying dance song of the season, watch Kiara Advani in a brand-new avatar in Bijli! Joined by Vicky Kaushal, the song from “Govinda Naam Mera” is composed by Sachin-Jigar, written by Vayu and sung by Mika Singh, Neha Kakkar and Sachin-Jigar. Inviting you to come shake a leg to Bijli, take care as to not get a shock with this one!\n\n#bijli #GovindaNaamMera #VickyKaushal #KiaraAdvani #SachinJigar #MikaSingh #NehaKakkar\n\nListen to the song here..\nSpotify - https://open.spotify.com/track/3hts3cIWNG8A2063si9GLP?si=AHwjjlgaRcWAPBiEllWjvw&utm_source=whatsapp\nAmazon Music - https://music.amazon.in/albums/B0BN3M4J6K?trackAsin=B0BN3PJ5PL&ref=dm_sh_iCxpsZdjvR1x4RB0JcHNv4EXA\nJioSaavn - https://www.saavn.com/p/album/hindi/bijli-from-govinda-naam-mera-2022/JOQc4svrtPI_?referrer=svn_source=share&svn_medium=com.whatsapp&utm_source=share&utm_medium=com.whatsapp\nHungama -\n https://www.hungama.com/album/bijli-from-govinda-naam-mera/96347285/\nGaana - https://gaana.com/album/bijli-from-govinda-naam-mera\nWynk Music - https://open.wynk.in/4t5dXdQWdvb?~destination=whatsapp&~feature=wynk_share&~content_id=srch_sonymusic_196589695147_INS172223779\nApple - https://music.apple.com/in/album/bijli-from-govinda-naam-mera/1655825134?i=1655825138\n\nMusic Composer: Sachin- Jigar\nSingers: Mika Singh, Neha Kakkar & Sachin- Jigar\nLyrics: Vayu\nArrangements: Sachin- Jigar\nProgramming: Abhijeet Nalani\nAdditional Programming: Abhishek Singh\nMusic Production Head: Romil Ved\nMixed and Master By: Eric Pillai @ FSOB Studios\nAssistant Mix & Master Engineer: Michael Edwin Pillai\n\nLive Instruments\nUkelele & Guitars: Keba Jeremiah\nStrokes: Tapas Roy\nLive percussion arranged by: Krishna Kishor \nPerformed by: K V Prasad, Krishna Kishor, Tappas Naresh \nChorus: Lavitha Lobo, Aishwarya , Sandhya and \nSargam choir Chennai\nRecorded by: Mani Ratham at the Mystics room\nChoreography by Ganesh Acharya\n\nLyrics:- \nAye Suno Suno Suno…\nSabko Tarsane\nMohalle Mai Aag Lagane\nApna Magic Barsane\nAa Gayi Hai Kolhapur Ki Bijli\n\nOoho!!\n\nAai Ga\n\nNako Re Nako!\n\nAyee Pyaar Ka Yeh Taar Bada Lamba\nEk Chadha Ke Chadh Gaya Mai Khamba\n\nAare Pyaar Ka Yeh Taar Bada Lamba\nEk Chadha Ke Chadh Gaya Mai Khamba\n\nLalitpur Mai London Mai\nAashiq Gire Darjan Mai\n\nHooo Lalitpur Mai London Mai\nAashiq Gire Darjan Mai\nThumka Laga Toh Nazar Fisli\n\nOh Haaye Re Meri Bijli Bijli Bijli Bijli Bijli\nOh Haaye Re Meri Bijli Bijli Bijli Bijli Bijli\n\nCurrent Maare Bijli Bijli Bijli Bijli Bijli… Bijli… Bijli\n\nOhh Tu Mila Aah Ah Aah Ah Aah Ah\nToh Dil Pe Katiya Padi Dil Pe Katiya Padi\n\nOhh Tu Mila Aah Ah Aah Ah Aah Ah\nToh Dil Pe Katiya Padi Dil Pe Katiya Padi\nJo Chuaa Aah Ah Aah Ah Aah\nToh Ho Gayi Khatiya Khadi\nHo Gayi Khatiya Khadi\n\nLalitpur Mai London Mai\nHaaye Ek Mai Sau Darjan Mai\n\nLalitpur Mai London Mai\nEk Mai Sau Darjan Mai\nTujhko Mai Dil Dungi Quickly\n\nOh Aayi Re Aayi Bijli Bijli Bijli Bijli Bijli\nOh Aayi Re Aayi Bijli Bijli Bijli Bijli Bijli\n\nOh Haaye Re Meri Bijli Bijli Bijli Bijli Bijli\nOh Haaye Re Meri Bijli Bijli Bijli Bijli Bijli\n\nCurrent Maare Bijli Bijli Bijli Bijli Bijli… Bijli… Bijli\n\nHoo Ho Ho Char Sau Chalees Ka Current Maare Re ke\nBijli Bijli Bijli Bijli Bijli\n\nHoo Ho Ho Hosh Udane Ke Talent Saare Hai\nBijli Bijli Bijli Bijli Bijli\n\nHoo Ho Ho Tere Aage Government Haare Hai\nBijli Bijli Bijli Bijli Bijli\n\nOh Haaye Re Meri Bijli Bijli Bijli Bijli Bijli\nOh Haaye Re Meri Bijli Bijli Bijli Bijli Bijli… Bijli… Bijli\n\nAudio on Sony Music Entertainment India Pvt. Ltd (C) 2022\n👉 Subscribe To Sony Music India YouTube - http://bit.ly/SonyMusic_YouTube\n👉 Like us : Facebook - https://www.facebook.com/SonyMusicIndia \n👉 Follow us : Instagram - https://www.instagram.com/sonymusicindia\n👉 Follow us : Twitter - https://twitter.com/sonymusicindia",
            "tags": [
                "Sony Music India",
                "Sony Music",
                "Latest Hits",
                "trending song 2022",
                "Bijli",
                "Govinda Naam Mera",
                "Vicky Kaushal",
                "Kiara Advani",
                "Sachin-Jigar",
                "Mika Singh",
                "Neha kakkar",
                "best song",
                "# dance",
                "dance",
                "no1 song",
                "full song#vickuy",
                "#Bijli",
                "#GovindaNaamMera",
                "#VickyKausha",
                "#KiaraAdvan",
                "#NehaKakkar",
                "#MikaSingh",
                "hindi songs",
                "dance song",
                "govinda song",
                "song",
                "chikni chameli",
                "kiara advani",
                "vicky",
                "katrina",
                "sony music India",
                "bijali",
                "cuurent mare bijli",
                "party",
                "#dance"
            ],
            "channelTitle": "Sony Music India",
            "publishedAt": "2022-11-25T05:30:11Z"
        },
        {
            "id": "f73ec65d-c8a5-4a35-ab0d-0808b40d7a7c",
            "videoId": "fP8gQlThTGU",
            "title": "Veera Simha Reddy - Jai Balayya Mass Anthem Lyric | Nandamuri Balakrishna | Shruti Haasan | Thaman S",
            "thumbnail": "https://i.ytimg.com/vi/fP8gQlThTGU/maxresdefault.jpg",
            "duration": "PT3M50S",
            "description": "Jai Balayya (Mass Anthem)\nSinger - Kareemullah \nLyrics - Ramjogayya sastry \nProgrammed And Arranged By Thaman S\nMusical Bands - Band Thamania & Gongura Band \nLive Percussions - Anandan Sivamani \nLive Percussions - Krishna Kishore \nFolk Rhythm - Vaniyambadi illam Puyal \nSound Indian Tapes - Lakshmi Narayana,Raju,Vedha,Jagan Mohan,Jaya Prakash,Lakshmi Kanth,Pyare Lal  \nThalam - Veeda \nNadaswaram - Sivakumar \nTrumpet - Babu \nGuitar - GodFray \nVocal Supervision -Sri Krishna\nMale Chours - Sri Krishna,Dhanunjay,Saicharan\nFemale Chours - Padmaja Vrusha Rachita Padmapriya Reshma Adviteeya,Pratyusha & Ramya \nSong Recorded @Prasad Studio ( Hyd ) ,V Studio ( Chennai ) Uno Records Studios by Osho V , Biju\nMixed & Mastered By Shadab Rayeen At \nNew Edge Mumbai & New Edge (Ny) \nAssisted By - Pukhraj  & Anup \nMusicians Co Ordinator - Manikandan K\nStudio Manager - Seenu & Sridhar \nStudio Assistance - Kannan,Lingam,Raju & Ranjith\n\nMovie Details:\nCast : NATASIMHAM Nandamuri Balakrishna, Shruti Haasan, Varalaxmi Sarathkumar, Honey Rose and Duniya Vijay\nStory-Screenplay-Direction : Gopichandh Malineni\nProducers : Naveen Yerneni and Ravi Shankar Yalamanchili\nCEO : Cherry\nExecutive Producer : Chandu Ravipati\nMusic : Thaman S\nCinematographer : Rishi Punjabi\nEditing : Navin Nooli\nProduction Designer : A.S. Prakash\nFights : Ram-Laxman, VVenkat\nDialogues : Sai Madhav Burra\nLyrics : Rama Jogaiah Sastry\nChoreography : Sekhar VJ, Shankar\nChief-Co Director : Kurra Rangarao\nCo-Directors : Gulabi Srinu and Nimmagadda Srikanth\nDirection Team: Prakash Dussa, Gajjala Bhaskar Reddy, Ramananda Sagar, Surya Guddati, Jyothi Prakash, Rithica Devireddy, Hemanth C. Yoganand\nPRO : Vamsi – Sekhar\nPublicity Designer : Working Title Shiva\nPublicity : Baba Sai Kumar\nMarketing : First Show\nLine Producer : Bala Subhramanyam KVV\nDI : Annapurna Studios\nColorist : Venu Gopal Rao. J\nAssociate Editors: N. Durga Prakash, Srinivas Nadiminti\nOnline Editor: Venkat Jalagam\nMaking: Krishna Reddy\n\nMusic Label - Sony Music Entertainment India Pvt. Ltd.\n\n© 2022 Sony Music Entertainment India Pvt. Ltd.\n\nSubscribe Now: http://bit.ly/SonyMusicSouthVevo\nSubscribe Now: http://bit.ly/SonyMusicSouthYT\nFollow us: https://www.instagram.com/sonymusic_south/\nFollow us: Twitter: https://twitter.com/SonyMusicSouth\nLike us: Facebook: https://www.facebook.com/SonyMusicSouth",
            "tags": [
                "Veera Simha Reddy Motion Poster",
                "Nandamuri Balakrishna",
                "Shruti Haasan",
                "Gopichandh Malineni",
                "Thaman S",
                "Sai Madhav Burra",
                "NBK107",
                "Nandamuri Balakrishna Movies",
                "Shruti Haasan Movies",
                "GopichandhMalineni Movies",
                "Thaman Songs",
                "Thaman Music",
                "2022 Latest Telugu Movies",
                "Latest Telugu Teasers 2022",
                "Jai Ballaya Mass Anthem",
                "Jai Ballaya",
                "jai ballaya song",
                "jai balayya video song"
            ],
            "channelTitle": "Sony Music South",
            "publishedAt": "2022-11-25T04:59:05Z"
        }
    ]
};